SELECT
DEVICE_PLATFORM,
SIT_SITE_ID,
COALESCE(OM.SOURCE_SESSION_L2,'NULO') AS ORIGIN_PATH,
FIRST_DS_USER,
FECHA_CUMPLE_AHA,
COALESCE(OM.SOURCE_SESSION_L1,'NULO') AS NEGOCIO,
COALESCE(OM.TEAM,'NULO') AS TEAM,
SUM(CONVERTION_W) AS CONVERTIONS

from meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_AHA_MOMENT_USERS as A
LEFT JOIN `meli-sbox.MPLAY.LK_MPLAY_SOURCE_TYPE_ORIGIN_SESSION` AS OM   ON OM.SOURCE_TYPE = a.ORIGIN_PATH
GROUP BY ALL
