SELECT
DEVICE_PLATFORM,
SIT_SITE_ID,
COALESCE(OM.SOURCE_SESSION_L2,'NULO') AS ORIGIN_PATH,
FECHA_CONV,
COALESCE(OM.SOURCE_SESSION_L1,'NULO') AS NEGOCIO,
COALESCE(OM.TEAM,'NULO') AS TEAM,
SUM(CONVERTION_W) AS CONVERTIONS,
SUM(COALESCE(A.RET_1_30,0)*CONVERTION_W) AS RET_1_30,
SUM(COALESCE(A.RET_31_60,0)*CONVERTION_W) AS RET_31_60,
SUM(COALESCE(A.AHA_MOMENT,0)*CONVERTION_W) AS AHA_MOMENT
FROM `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS` as A
LEFT JOIN `meli-sbox.MPLAY.LK_MPLAY_SOURCE_TYPE_ORIGIN_SESSION` AS OM   ON OM.SOURCE_TYPE = a.ORIGIN_PATH
GROUP BY ALL
