-- En esta query solo vamos a traer las siguientes columnas: MONTH, SITE, TOTAL_USERS_RECO, TVM_PREV, TVM_ACT, ATV_PREV, ATV_ACT, CVR_PREV, CVR_ACT
-- Esto es para la hoja 1 y vamos a armar lo siguiente:
-- Filtros: Por SITE,
WITH BASE_USERS AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    DS,
    DATE_TRUNC(DS, MONTH) AS TIME_FRAME_ID,
    UPPER(DEVICE_PLATFORM) AS DEVICE_PLATFORM,
    PLAYBACK_TIME_MILLISECONDS,
    PLAYBACK_TIME_MILLISECONDS_CAST,
    START_PLAY_TIMESTAMP,
    PLAYBACK_TIME_MILLISECONDS / 60000.0 AS VIEW_MINUTES,
    PLAYBACK_TIME_MILLISECONDS_CAST / 60000.0 AS VIEW_CAST_MINUTES
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND DS <= CURRENT_DATE() - 1
),

USERS_RECOVERED AS (
  SELECT
    *,
    LAG(DS) OVER (PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP) AS DS_ANT,
    DATE_DIFF(DS, LAG(DS) OVER (PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP), DAY) AS DIF_DAYS,
    'RECOVERED' AS FLAG_USER
  FROM BASE_USERS
),

USER_CONS AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    TIME_FRAME_ID,
    SUM(VIEW_MINUTES) AS TVM,
    SUM(CASE WHEN DEVICE_PLATFORM LIKE '%TV%' THEN VIEW_MINUTES ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN DEVICE_PLATFORM LIKE '%MOBILE%' THEN VIEW_MINUTES ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN DEVICE_PLATFORM LIKE '%DESK%' THEN VIEW_MINUTES ELSE 0 END) AS TOTAL_DESKTOP,
    SUM(VIEW_CAST_MINUTES) AS TOTAL_CAST
  FROM USERS_RECOVERED
  GROUP BY 1, 2, 3
),

FLAG_PLATFORM_ACTUAL AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    TIME_FRAME_ID,
    CONCAT(
        CASE WHEN TOTAL_TV > 0 THEN 'SMART' ELSE '' END,
        CASE WHEN TOTAL_MOBILE > 0 THEN 'MOBILE' ELSE '' END,
        CASE WHEN TOTAL_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END,
        CASE WHEN TOTAL_CAST > 0 THEN 'CAST' ELSE '' END
      ) AS PLATFORM_ACTUAL
  FROM USER_CONS
)
SELECT 
  UR.SIT_SITE_ID,
  UR.TIME_FRAME_ID,
  FPA.PLATFORM_ACTUAL,
  COUNT(DISTINCT UR.USER_ID) AS TOTAL_USERS,
  SUM(UR.VIEW_MINUTES) AS TVM,
  SUM(UR.VIEW_MINUTES) / COUNT(DISTINCT UR.USER_ID) AS ATV
FROM USERS_RECOVERED UR
LEFT JOIN FLAG_PLATFORM_ACTUAL FPA
  ON UR.SIT_SITE_ID = FPA.SIT_SITE_ID
  AND UR.USER_ID = FPA.USER_ID
  AND UR.TIME_FRAME_ID = FPA.TIME_FRAME_ID
WHERE UR.DS BETWEEN '2025-01-01' AND CURRENT_DATE()
  AND UR.DIF_DAYS > 30
GROUP BY 1, 2, 3, 4, 5
