DECLARE DATE_FROM DATE;
DECLARE DATE_TO DATE;
DECLARE SITES ARRAY<STRING>;
SET DATE_FROM = '2025-01-01';
SET DATE_TO = CURRENT_DATE() - 1;
SET SITES = ['MLA','MLB','MLM','MLC','MCO','MPE','MLU','MEC'];

WITH CONTENT_BASE AS (
  SELECT
    C.SIT_SITE_ID,
    C.ORIGINAL_TITLE,
    C.TITLE_ADJUSTED,
    CASE
      WHEN C.CONTENT_TYPE = 'MOVIE' THEN 'MOVIE'
      ELSE 'SERIES'
    END AS CONTENT_TYPE_ADJUSTED,
    C.CONTENT_ID,
    CASE
      WHEN C.CONTENT_PROVIDER = 'SONY' THEN 'SONY'
      WHEN C.CONTENT_PROVIDER IN ('PARAMOUNT', 'CBS','PARAMOUNTTL','PARAMOUNBR') THEN 'PARAMOUNT'
      WHEN C.CONTENT_PROVIDER = 'MPLAYORIGINALS' THEN 'MPLAYORIGINALS'
      WHEN C.CONTENT_PROVIDER IN ('NBCUAVOD', 'UNIVERSALPLUS') OR P.CHANNEL_ID IN ('3062aa4b18ff46ed8d59fe6c3f088bc6','167e27fd5bb84dfabde7103648b9a96b','3f1cc2cccea34b9490b00d6ac514e225','63b08af757040aebdb2d23246fcf71a','9e95f70f53e54e3b86850c2d9a7b1df5','24d2994c2807438eb89c817534ed76db','bb853ee1e9264f018031baab6ea1e3d2') THEN 'NBCU'
      ELSE C.CONTENT_PROVIDER 
    END AS CONTENT_PROVIDER_ADJUSTED,
    C.GENRE
  FROM meli-bi-data.WHOWNER.LK_MKT_MPLAY_CATALOGUE AS C
  LEFT JOIN meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS AS P
    ON C.CONTENT_ID = P.CONTENT_ID
),
NEW_RET_RECO AS (
  SELECT 
    P.PLAY_ID,
    P.CUS_CUST_ID,
    P.USER_ID,
    P.SIT_SITE_ID,
    P.PLAYBACK_TIME_MILLISECONDS,
    P.START_PLAY_TIMESTAMP,
    P.SESSION_ID,
    P.DS,
    P.CONTENT_ID, 
    C.ORIGINAL_TITLE,
    C.CONTENT_TYPE_ADJUSTED,
    C.CONTENT_PROVIDER_ADJUSTED,
    DATE_TRUNC(P.DS,MONTH) AS TIME_FRAME_ID,
    CASE
      WHEN LAG(P.DS,1) OVER (PARTITION BY P.SIT_SITE_ID, P.USER_ID ORDER BY START_PLAY_TIMESTAMP ASC) IS NULL THEN 'NEW'
      WHEN DATE_DIFF(DS, LAG(DS, 1) OVER (PARTITION BY P.SIT_SITE_ID, P.USER_ID ORDER BY START_PLAY_TIMESTAMP ASC), DAY) <= 30 THEN 'RETAINED'
      WHEN DATE_DIFF(DS, LAG(DS, 1) OVER (PARTITION BY P.SIT_SITE_ID, P.USER_ID ORDER BY START_PLAY_TIMESTAMP ASC), DAY) > 30 THEN 'RECOVERED'
    ELSE NULL END AS FLAG_N_R
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
  LEFT JOIN CONTENT_BASE AS C
    ON P.SIT_SITE_ID = C.SIT_SITE_ID
    AND P.CONTENT_ID = C.CONTENT_ID
  WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20 
    AND DS <= CURRENT_DATE-1
),
ATTR_TIME_FRAME_ELEGIDO AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    TIME_FRAME_ID,
    FLAG_N_R
  FROM NEW_RET_RECO
  QUALIFY ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, USER_ID, TIME_FRAME_ID ORDER BY START_PLAY_TIMESTAMP ASC) = 1
),
CRUCE_FLAG AS (
  SELECT
    A.*,
    E.FLAG_N_R AS FLAG_N_R_FINAL
  FROM NEW_RET_RECO AS A
  LEFT JOIN ATTR_TIME_FRAME_ELEGIDO AS E
    ON E.SIT_SITE_ID = A.SIT_SITE_ID
    AND E.USER_ID = A.USER_ID
    AND E.TIME_FRAME_ID = A.TIME_FRAME_ID
),
RESUME_USERS_TIMEFRAME AS (
  SELECT
    CF.TIME_FRAME_ID,
    CF.SIT_SITE_ID,
    COUNT(DISTINCT CF.USER_ID) AS TOTAL_USERS,
    COUNT(CASE WHEN CF.FLAG_N_R_FINAL = 'NEW' THEN CF.USER_ID END) AS TOTAL_NEW_USERS,
    COUNT(CASE WHEN CF.FLAG_N_R_FINAL = 'RECOVERED' THEN CF.USER_ID END) AS TOTAL_RECOVERED_USERS,
    COUNT(CASE WHEN CF.FLAG_N_R_FINAL = 'RETAINED' THEN CF.USER_ID END) AS TOTAL_RETAINED_USERS
  FROM CRUCE_FLAG AS CF
  GROUP BY ALL
),
RESUME_CONTENT AS (
  SELECT
    CF.TIME_FRAME_ID,
    CF.SIT_SITE_ID,
    CF.CONTENT_ID,
    CF.ORIGINAL_TITLE,
    CF.CONTENT_TYPE_ADJUSTED,
    CF.CONTENT_PROVIDER_ADJUSTED,
    SUM(CF.PLAYBACK_TIME_MILLISECONDS / 60000) AS TVM,
    COUNT(DISTINCT CF.USER_ID) AS TOTAL_USERS_CONTENT,
    SAFE_DIVIDE(COUNT(DISTINCT CF.USER_ID), SUM(RUT.TOTAL_USERS)) AS SHARE_TOTAL_USERS,
    COUNT(DISTINCT CASE WHEN CF.FLAG_N_R_FINAL = 'NEW' THEN CF.USER_ID END) AS NEW_USERS_CONTENT,
    SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN CF.FLAG_N_R_FINAL = 'NEW' THEN CF.USER_ID END), SUM(RUT.TOTAL_NEW_USERS)) AS SHARE_NEW_USERS,
    COUNT(DISTINCT CASE WHEN CF.FLAG_N_R_FINAL = 'RECOVERED' THEN CF.USER_ID END) AS RECOVERED_USERS_CONTENT,
    SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN CF.FLAG_N_R_FINAL = 'RECOVERED' THEN CF.USER_ID END), SUM(RUT.TOTAL_RECOVERED_USERS)) AS SHARE_RECOVERED_USERS,
    COUNT(DISTINCT CASE WHEN CF.FLAG_N_R_FINAL = 'RETAINED' THEN CF.USER_ID END) AS RETAINED_USERS_CONTENT,
    SAFE_DIVIDE(COUNT(DISTINCT CASE WHEN CF.FLAG_N_R_FINAL = 'RETAINED' THEN CF.USER_ID END), SUM(RUT.TOTAL_RETAINED_USERS)) AS SHARE_RETAINED_USERS
  FROM CRUCE_FLAG AS CF
  LEFT JOIN RESUME_USERS_TIMEFRAME AS RUT
    ON CF.TIME_FRAME_ID = RUT.TIME_FRAME_ID
   AND CF.SIT_SITE_ID = RUT.SIT_SITE_ID
  GROUP BY ALL
),
CONTENT_RETENTION_M1 AS (
  SELECT
    CF.TIME_FRAME_ID,
    CF.SIT_SITE_ID,
    CF.CONTENT_ID,
    COUNT(DISTINCT CF.USER_ID) AS TOTAL_USERS_CONTENT,
    COUNT(DISTINCT CM.USER_ID) AS TOTAL_USERS_RETENTION,
    ROUND(SAFE_DIVIDE(COUNT(DISTINCT CM.USER_ID), COUNT(DISTINCT CF.USER_ID)),4) AS RATE_RETENTION_M1
  FROM CRUCE_FLAG AS CF
  LEFT JOIN CRUCE_FLAG AS CM
    ON CF.TIME_FRAME_ID = DATE_ADD(CM.TIME_FRAME_ID, INTERVAL 1 MONTH)
   AND CF.SIT_SITE_ID = CM.SIT_SITE_ID
    AND CF.USER_ID = CM.USER_ID
  GROUP BY ALL
)
SELECT
  R.TIME_FRAME_ID,
  R.SIT_SITE_ID,
  R.CONTENT_ID,
  R.ORIGINAL_TITLE,
  R.CONTENT_TYPE_ADJUSTED AS CONTENT_TYPE,
  R.CONTENT_PROVIDER_ADJUSTED AS CONTENT_PROVIDER,
  R.TVM,
  R.TOTAL_USERS_CONTENT,
  R.SHARE_TOTAL_USERS,
  R.NEW_USERS_CONTENT,
  R.SHARE_NEW_USERS,
  R.RECOVERED_USERS_CONTENT,
  R.SHARE_RECOVERED_USERS,
  R.RETAINED_USERS_CONTENT,
  R.SHARE_RETAINED_USERS,
  CR.RATE_RETENTION_M1
FROM RESUME_CONTENT AS R
LEFT JOIN CONTENT_RETENTION_M1 AS CR
  ON R.TIME_FRAME_ID = CR.TIME_FRAME_ID
 AND R.SIT_SITE_ID = CR.SIT_SITE_ID
 AND R.CONTENT_ID = CR.CONTENT_ID