-- description: Métricas de consumo (viewers logueados y TVM) por título, tipo de contenido, proveedor y etapa del ciclo de vida del usuario
-- domain: behaviour
-- product: mplay
-- use_case: reporting
-- grain: site, snapshot_date, life_cycle_stage, content_type_adjusted, nbcu_flag, title
-- time_grain: aggregated_period
-- date_column: V.DS
-- date_filter: between (relative)
-- threshold_rule: playback_time >= 20s
-- metrics:
--   - VIEWERS_LOGGED: usuarios logueados únicos con al menos una reproducción >= 20s
--   - TVM: minutos totales reproducidos por usuarios logueados con threshold 20s
-- tables_read:
--   - WHOWNER.BT_MKT_MPLAY_PLAYS
--   - WHOWNER.BT_MKT_MPLAY_SESSION
--   - WHOWNER.LK_MKT_MPLAY_CATALOGUE
--   - MPLAY.LAST_MPLAY_USER_LIFECYCLE_SNAPSHOT
-- joins:
--   - PLAYS.SESSION_ID = SESSION.SESSION_ID
--   - PLAYS.SIT_SITE_ID = CATALOGUE.SIT_SITE_ID
--   - PLAYS.CONTENT_ID = CATALOGUE.CONTENT_ID
--   - PLAYS.CUS_CUST_ID = USER_LIFECYCLE.USER_ID
-- owner: data_team


DECLARE DATE_FROM DATE;
DECLARE DATE_TO DATE;
DECLARE SITES ARRAY<STRING>;
SET DATE_FROM = CURRENT_DATE() - 30;
SET DATE_TO = CURRENT_DATE();
SET SITES = ['MLA','MLB','MLM'];

WITH CATALOG1 AS (
  SELECT 
    C.SIT_SITE_ID,
    C.CONTENT_TYPE,
    C.CONTENT_ID,
    CASE 
      WHEN C.CONTENT_TYPE IN ('EPISODE','SHOW') THEN 'SERIES' 
      ELSE C.CONTENT_TYPE
    END AS CONTENT_TYPE_ADJUSTED,
    C.SEASON_NUMBER,
    C.EPISODE_NUMBER,
    C.ORIGINAL_TITLE AS ORIGINAL_TITLE_2,
    C.TITLE_ADJUSTED,
    C.CONTENT_PROVIDER,
    C.GENRE,
    C.RUNTIME
  FROM `WHOWNER.LK_MKT_MPLAY_CATALOGUE` C
  LEFT JOIN (
    SELECT
      CONTENT_ID,
      SHOW_ID,
      SIT_SITE_ID,
      ORIGINAL_TITLE
    FROM `WHOWNER.LK_MKT_MPLAY_CATALOGUE` 
    WHERE CONTENT_TYPE = 'SHOW'
  ) S 
    ON C.SHOW_ID = S.CONTENT_ID 
    AND C.SIT_SITE_ID = S.SIT_SITE_ID
), 
ALL_VIEWS AS (
  SELECT DISTINCT
    P.SIT_SITE_ID, 
    P.CUS_CUST_ID,
    P.DS,
    DATE_TRUNC(P.DS, MONTH) AS MONTH_ID,
    C1.CONTENT_TYPE_ADJUSTED,
    C1.CONTENT_PROVIDER,
    C1.TITLE_ADJUSTED,
    S.ORIGIN_PATH,
    LAG (P.DS) OVER(PARTITION BY P.SIT_SITE_ID, P.CUS_CUST_ID ORDER BY P.DS) AS DS_PREV,
    MIN(P.DS) OVER (PARTITION BY P.SIT_SITE_ID, P.CUS_CUST_ID) AS FIRST_VIEW,
    MAX(P.DS) OVER (PARTITION BY P.SIT_SITE_ID, P.CUS_CUST_ID) AS LAST_VIEW,
    MIN(P.DS) OVER (PARTITION BY P.SIT_SITE_ID, P.CUS_CUST_ID, DATE_TRUNC(P.DS, MONTH)) AS FIRST_VIEW_MONTH,
    MAX(P.DS) OVER (PARTITION BY P.SIT_SITE_ID, P.CUS_CUST_ID, DATE_TRUNC(P.DS, MONTH)) AS LAST_VIEW_MONTH,
    SUM(P.PLAYBACK_TIME_MILLISECONDS/60000) AS TVM
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
  LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` S 
    ON P.SESSION_ID = S.SESSION_ID
  LEFT JOIN CATALOG1 C1 
    ON P.SIT_SITE_ID = C1.SIT_SITE_ID 
    AND P.CONTENT_ID = C1.CONTENT_ID
  WHERE P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
    AND P.SIT_SITE_ID IN UNNEST(SITES)
  GROUP BY ALL
), 
FIRST_VIEW_MONTH AS (
  SELECT DISTINCT 
    SIT_SITE_ID,
    CUS_CUST_ID,
    DS,
    MONTH_ID,
    ORIGIN_PATH
    --O.NEGOCIO AS RET_ORIGIN_GROUP,
    --O.ACCESS AS RET_ACCESS
  FROM ALL_VIEWS V
  --LEFT JOIN `meli-sbox.MPLAY.LK_MPLAY_ORIGIN` O ON V.ORIGIN_PATH = O.ORIGIN
  QUALIFY ROW_NUMBER() OVER(PARTITION BY MONTH_ID, CUS_CUST_ID ORDER BY V.DS ASC) = 1 
)
SELECT 
  V.SIT_SITE_ID,
  SNAPSHOT_DATE,
  CASE 
    WHEN SEGMENT_LIFE_CYCLE IN ('1.ACQUISITION','2.CONSIDERATION','3.ACTIVATION','4.EARLY ENGAGEMENT') THEN 'ACQUISITION'
    WHEN SEGMENT_LIFE_CYCLE IN ('5.RETENTION') THEN 'ENGAGEMENT'
    ELSE 'OTROS'
  END AS LIFE_CYCLE_STAGE, ---TRAE EL ÚLTIMO SEGMENTO
  CONTENT_TYPE_ADJUSTED,
  CASE 
    WHEN V.CONTENT_PROVIDER IN ('NBCUAVOD','UNIVERSALPLUS') THEN 'NBCU' 
    ELSE 'NOT_NBCU' 
  END AS NBCU_FLAG,
  V.TITLE_ADJUSTED,
  COUNT(DISTINCT V.CUS_CUST_ID) AS VIEWERS_LOGGED,
  SUM (TVM) AS TVM
FROM ALL_VIEWS V
LEFT JOIN `meli-sbox.MPLAY.LAST_MPLAY_USER_LIFECYCLE_SNAPSHOT` LC 
  ON V.CUS_CUST_ID = CAST(LC.USER_ID AS INT) 
WHERE V.DS >= DATE_FROM
  AND V.DS < DATE_TO
  AND SEGMENT_LIFE_CYCLE IN ('1.ACQUISITION','2.CONSIDERATION','3.ACTIVATION','4.EARLY ENGAGEMENT','5.RETENTION')
  AND V.TITLE_ADJUSTED IS NOT NULL
GROUP BY ALL
ORDER BY VIEWERS_LOGGED DESC;