WITH BASE_USER_CONTENT AS (
    SELECT 
    P.PLAY_ID,
    P.CUS_CUST_ID,
    P.USER_ID,
    P.SIT_SITE_ID,
    P.PLAYBACK_TIME_MILLISECONDS,
    P.START_PLAY_TIMESTAMP,
    P.SESSION_ID,
    P.DS,
    P.CONTENT_ID, 
    C.ORIGINAL_TITLE,
    C.CONTENT_TYPE_ADJUSTED,
    C.CONTENT_PROVIDER_ADJUSTED,
    DATE_TRUNC(P.DS,MONTH) AS TIME_FRAME_ID,
    R.LIFE_CYCLE,
    R.FLAG_AHA
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
  LEFT JOIN meli-sbox.MPLAY.MPLAY_CONTENT_ADJUSTED AS C
    ON P.SIT_SITE_ID = C.SIT_SITE_ID
    AND P.CONTENT_ID = C.CONTENT_ID
  LEFT JOIN `meli-bi-data.WHOWNER.DM_MKT_MPLAY_RAW_PLAYS` AS R
    ON P.USER_ID = R.USER_ID
    AND P.SIT_SITE_ID = R.SIT_SITE_ID
    AND DATE_TRUNC(P.DS,MONTH) = DATE_TRUNC(R.TIM_DAY,MONTH)
  WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20 
    AND DS <= CURRENT_DATE-1
    AND R.TIME_FRAME = 'MONTHLY'
),
RESUME_TIMEFRAME AS (
  
)