DECLARE DATE_FROM DATE;
DECLARE DATE_TO DATE;
DECLARE SITES ARRAY<STRING>;
SET DATE_FROM = '2025-10-01';
SET DATE_TO = '2025-12-31';
SET SITES = ['MLA','MLB','MLM','MLC','MCO','MPE','MLU','MEC'];

WITH NEW_RET_RECO AS (
  SELECT 
    P.PLAY_ID,
    P.CUS_CUST_ID,
    P.USER_ID,
    P.SIT_SITE_ID,
    P.DS,
    P.CONTENT_ID, 
    C.ORIGINAL_TITLE,
    C.CONTENT_TYPE_ADJUSTED,
    C.CONTENT_PROVIDER_ADJUSTED,
    DATE_TRUNC(P.DS,MONTH) AS TIME_FRAME_ID,
    R.LIFE_CYCLE
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
  LEFT JOIN `meli-sbox.MPLAY.MPLAY_CONTENT_ADJUSTED` AS C
    ON P.SIT_SITE_ID = C.SIT_SITE_ID
    AND P.CONTENT_ID = C.CONTENT_ID
  LEFT JOIN `meli-bi-data.WHOWNER.DM_MKT_MPLAY_RAW_PLAYS` AS R
    ON P.USER_ID = R.USER_ID
    AND P.SIT_SITE_ID = R.SIT_SITE_ID
    AND DATE_TRUNC(P.DS,MONTH) = DATE_TRUNC(R.TIM_DAY,MONTH)
  WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20 
    AND DS <= CURRENT_DATE-1
),
USER_MONTH_CONTENT_FLAG AS (
  SELECT
    NRR.SIT_SITE_ID,
    NRR.USER_ID,
    NRR.TIME_FRAME_ID,
    NRR.LIFE_CYCLE,
    CASE
      WHEN COUNT(DISTINCT CONTENT_TYPE_ADJUSTED) = 1 AND MAX(CONTENT_TYPE_ADJUSTED) = 'SERIES' THEN 'SERIES'
      WHEN COUNT(DISTINCT CONTENT_TYPE_ADJUSTED) = 1 AND MAX(CONTENT_TYPE_ADJUSTED) = 'MOVIE' THEN 'MOVIE'
      WHEN COUNT(DISTINCT CONTENT_TYPE_ADJUSTED) > 1 THEN 'BOTH'
      ELSE NULL
    END AS FLAG_CONTENT
  FROM NEW_RET_RECO AS NRR
  WHERE CONTENT_TYPE_ADJUSTED IS NOT NULL
  GROUP BY ALL
)
-- CONSULTA FINAL
SELECT
  UMCF.SIT_SITE_ID,
  UMCF.TIME_FRAME_ID,
  UMCF.LIFE_CYCLE,
  UMCF.FLAG_CONTENT,
  COUNT(DISTINCT UMCF.USER_ID) AS TOTAL_USERS
FROM USER_MONTH_CONTENT_FLAG AS UMCF
WHERE UMCF.SIT_SITE_ID IN UNNEST(SITES)
  AND UMCF.TIME_FRAME_ID BETWEEN DATE_TRUNC(DATE_FROM, MONTH) AND DATE_TRUNC(DATE_TO, MONTH)
GROUP BY ALL