DECLARE DATE_FROM DATE;
DECLARE DATE_TO DATE;
DECLARE SITES ARRAY<STRING>;
SET DATE_FROM = '2025-01-01';
SET DATE_TO = CURRENT_DATE() - 1;
SET SITES = ['MLA','MLB','MLM','MLC','MCO','MPE','MLU','MEC'];

WITH CONTENT_BASE AS (
  SELECT
    C.SIT_SITE_ID,
    C.ORIGINAL_TITLE,
    C.TITLE_ADJUSTED,
    CASE
      WHEN C.CONTENT_TYPE = 'MOVIE' THEN 'MOVIE'
      ELSE 'SERIES'
    END AS CONTENT_TYPE_ADJUSTED,
    C.CONTENT_ID,
    CASE
      WHEN C.CONTENT_PROVIDER = 'SONY' THEN 'SONY'
      WHEN C.CONTENT_PROVIDER IN ('PARAMOUNT', 'CBS','PARAMOUNTTL','PARAMOUNBR') THEN 'PARAMOUNT'
      WHEN C.CONTENT_PROVIDER = 'MPLAYORIGINALS' THEN 'MPLAYORIGINALS'
      WHEN C.CONTENT_PROVIDER IN ('NBCUAVOD', 'UNIVERSALPLUS') OR P.CHANNEL_ID IN ('3062aa4b18ff46ed8d59fe6c3f088bc6','167e27fd5bb84dfabde7103648b9a96b','3f1cc2cccea34b9490b00d6ac514e225','63b08af757040aebdb2d23246fcf71a','9e95f70f53e54e3b86850c2d9a7b1df5','24d2994c2807438eb89c817534ed76db','bb853ee1e9264f018031baab6ea1e3d2') THEN 'NBCU'
      ELSE C.CONTENT_PROVIDER 
    END AS CONTENT_PROVIDER_ADJUSTED,
    C.GENRE
  FROM meli-bi-data.WHOWNER.LK_MKT_MPLAY_CATALOGUE AS C
),
NEW_RET_RECO AS (
  SELECT 
    P.PLAY_ID,
    P.CUS_CUST_ID,
    P.USER_ID,
    P.SIT_SITE_ID,
    P.PLAYBACK_TIME_MILLISECONDS,
    P.START_PLAY_TIMESTAMP,
    P.SESSION_ID,
    P.DS,
    P.CONTENT_ID, 
    C.ORIGINAL_TITLE,
    C.CONTENT_TYPE_ADJUSTED,
    C.CONTENT_PROVIDER_ADJUSTED,
    DATE_TRUNC(P.DS,MONTH) AS TIME_FRAME_ID
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
  LEFT JOIN CONTENT_BASE AS C
    ON P.SIT_SITE_ID = C.SIT_SITE_ID
    AND P.CONTENT_ID = C.CONTENT_ID
  WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20 
    AND DS <= CURRENT_DATE-1
),
RESUME_CONTENT AS (
  SELECT
    CF.TIME_FRAME_ID,
    CF.SIT_SITE_ID,
    CF.CONTENT_ID,
    CF.ORIGINAL_TITLE,
    CF.CONTENT_TYPE_ADJUSTED,
    CF.CONTENT_PROVIDER_ADJUSTED,
    SUM(CF.PLAYBACK_TIME_MILLISECONDS/60000) AS TVM,
    COUNT(DISTINCT CF.USER_ID) AS TOTAL_USERS
  FROM CRUCE_FLAG AS CF
  GROUP BY ALL
)
SELECT * FROM BASE_PLATFORM_FINAL 