WITH BASE AS (
    SELECT
    C.SEASON_NUMBER AS SEASON_NUMBER,
    C.TITLE_ADJUSTED AS TITLE_ADJUSTED,
    C.RUNTIME AS RUNTIME,
    COUNT(DISTINCT CASE WHEN(P.PLAYBACK_TIME_MILLISECONDS >= 20000) THEN P.USER_ID ELSE NULL END) AS VIEWERS,
    COUNT(DISTINCT P.CONTENT_ID) AS CANTIDAD_CONTENIDOS,
    COUNT(DISTINCT CONCAT( P.CONTENT_ID  , ' ',  P.USER_ID)) AS REPRODUCCIONES,
    SAFE_DIVIDE(SUM(IF((P.PLAYBACK_TIME_MILLISECONDS ) >= 20000, P.PLAYBACK_TIME_MILLISECONDS , NULL)), 60000) AS TVM
FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
LEFT JOIN `meli-bi-data.WHOWNER.LK_MKT_MPLAY_CATALOGUE` AS C 
    ON P.SIT_SITE_ID = C.SIT_SITE_ID
    AND  P.CONTENT_ID  = C.CONTENT_ID
WHERE (P.PLAYBACK_TIME_MILLISECONDS ) >= 20000 
AND (((P.DS) >= ((DATE_ADD(DATE_TRUNC(CURRENT_DATE('America/Buenos_Aires'), YEAR), INTERVAL -4 YEAR))) 
AND (P.DS) < ((DATE_ADD(DATE_ADD(DATE_TRUNC(CURRENT_DATE('America/Buenos_Aires'), YEAR), INTERVAL -4 YEAR), INTERVAL 5 YEAR))))) 
AND (((P.DS) >= ((DATE_ADD(DATE_TRUNC(CURRENT_DATE('America/Buenos_Aires'), MONTH), INTERVAL -5 MONTH))) 
AND (P.DS) < ((DATE_ADD(DATE_ADD(DATE_TRUNC(CURRENT_DATE('America/Buenos_Aires'), MONTH), INTERVAL -5 MONTH), INTERVAL 6 MONTH))))) 
AND (C..SEASON_NUMBER ) >= 1
GROUP BY 1, 2
LIMIT 30000
)
SELECT 
*,
SAFE_DIVIDE(TVM, VIEWERS * RUNTIME) AS COMPLETION_RATE
FROM BASE