WITH NEW_USERS_PREVIOUS_MONTH AS (
  SELECT
    USER_ID,
    DATE_ADD(DATE_TRUNC(TIM_DAY, MONTH), INTERVAL 1 MONTH) AS ANALYSIS_MONTH
  FROM `meli-bi-data.WHOWNER.DM_MKT_MPLAY_RAW_PLAYS`
  WHERE TIME_FRAME = 'MONTHLY' AND LIFE_CYCLE = 'NEW'
  GROUP BY 1, 2
),

CONTENT_VIEWERS_BASE AS (
  -- 1. Eliminamos duplicidad de usuario por contenido en el mismo mes
  SELECT
    DATE_TRUNC(P.DS, MONTH) AS MONTH_ID,
    P.CONTENT_ID,
    P.USER_ID,
    MAX(CASE WHEN N.USER_ID IS NOT NULL THEN 1 ELSE 0 END) AS IS_COHORT_NEW_M0
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
  INNER JOIN `meli-bi-data.WHOWNER.DM_MKT_MPLAY_RAW_PLAYS` AS R
    ON R.USER_ID = P.USER_ID
    AND DATE_TRUNC(P.DS, MONTH) = DATE_TRUNC(R.TIM_DAY, MONTH)
  LEFT JOIN NEW_USERS_PREVIOUS_MONTH AS N
    ON R.USER_ID = N.USER_ID
    AND DATE_TRUNC(R.TIM_DAY, MONTH) = N.ANALYSIS_MONTH
  WHERE R.TIME_FRAME = 'MONTHLY'
    AND P.PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND P.DS BETWEEN '2025-01-01' AND CURRENT_DATE - 1
  GROUP BY 1, 2, 3
),

CATALOG_CLEAN AS (
  -- 2. "Aplanamos" el catálogo para que cada ID sea único
  SELECT 
    CONTENT_ID,
    MAX(TITLE_ADJUSTED) AS TITLE_ADJUSTED,
    MAX(CASE WHEN CONTENT_TYPE = 'MOVIE' THEN 'MOVIE' ELSE 'SERIES' END) AS CONTENT_TYPE_ADJUSTED,
    MAX(CASE
      WHEN CONTENT_PROVIDER = 'SONY' THEN 'SONY'
      WHEN CONTENT_PROVIDER IN ('PARAMOUNT', 'CBS','PARAMOUNTTL','PARAMOUNBR') THEN 'PARAMOUNT'
      WHEN CONTENT_PROVIDER = 'MPLAYORIGINALS' THEN 'MPLAYORIGINALS'
      WHEN CONTENT_PROVIDER IN ('NBCUAVOD', 'UNIVERSALPLUS') THEN 'NBCU'
      ELSE CONTENT_PROVIDER 
    END) AS PROVIDER_ADJUSTED
  FROM `meli-bi-data.WHOWNER.LK_MKT_MPLAY_CATALOGUE`
  GROUP BY 1
),

AGGREGATED_TITLES AS (
  -- 3. SUM del total de viewers por cada título y mes
  SELECT 
    B.MONTH_ID,
    B.CONTENT_ID,
    COUNT(DISTINCT B.USER_ID) AS TOTAL_VIEWERS,
    SUM(B.IS_COHORT_NEW_M0) AS VIEWERS_NEW_M0,
    -- Calculamos el total mensual para el denominador del Pareto
    SUM(COUNT(DISTINCT B.USER_ID)) OVER (PARTITION BY B.MONTH_ID) AS TOTAL_MONTHLY_VIEWS
  FROM CONTENT_VIEWERS_BASE B
  GROUP BY 1, 2
),

PARETO_FINAL AS (
  -- 4. Ahora el cálculo de Pareto es sobre títulos únicos consolidados
  SELECT
    A.*,
    (SUM(A.TOTAL_VIEWERS) OVER (PARTITION BY A.MONTH_ID ORDER BY A.TOTAL_VIEWERS DESC) / A.TOTAL_MONTHLY_VIEWS) AS CUMULATIVE_SHARE_RATIO
  FROM AGGREGATED_TITLES A
)

-- 5. Resultado final filtrado
SELECT
  P.MONTH_ID,
  COALESCE(CAT.TITLE_ADJUSTED, 'Unknown Content') AS TITLE_ADJUSTED,
  CAT.CONTENT_TYPE_ADJUSTED,
  CAT.PROVIDER_ADJUSTED,
  P.TOTAL_VIEWERS,
  P.VIEWERS_NEW_M0,
  ROUND(SAFE_DIVIDE(P.VIEWERS_NEW_M0, P.TOTAL_VIEWERS) * 100, 4) AS PCT_NEW_M0,
  ROUND(P.CUMULATIVE_SHARE_RATIO * 100, 2) AS PARETO_PROGRESS_PCT
FROM PARETO_FINAL P
LEFT JOIN CATALOG_CLEAN CAT ON P.CONTENT_ID = CAT.CONTENT_ID
WHERE P.CUMULATIVE_SHARE_RATIO <= 0.80
ORDER BY P.MONTH_ID DESC, P.TOTAL_VIEWERS DESC;