WITH PLAYS AS (
    SELECT
        DS, DATE_TRUNC(PL.DS, MONTH) AS FECHA_MONTH, PL.SIT_SITE_ID, CAST(PL.user_id AS STRING) AS cus_cust_id, 
        PL.CONTENT_ID, PL.CHANNEL_ID, PL.PLAY_ID, PL.START_PLAY_TIMESTAMP,
        CASE 
            WHEN DEVICE_PLATFORM IN ('/mobile/android','/mobile/ios', '/web/mobile') THEN 'MOBILE'
            WHEN DEVICE_PLATFORM IN ('/tv/Mac OS X','/tv/Tizen','/tv/Web0S','/tv/android','/tv/macOS','/tv/webos') THEN 'SMART_TV'
            WHEN DEVICE_PLATFORM IN ('/web/desktop') THEN 'DESKTOP'
        END AS DEVICE_AJUSTADO, 
        PL.PLAYBACK_TIME_MILLISECONDS/60000 AS TOTAL_MIN_VIEWS
    FROM `WHOWNER.BT_MKT_MPLAY_PLAYS` PL
    WHERE DS BETWEEN '2024-01-01' AND CURRENT_DATE -1
    AND PLAYBACK_TIME_MILLISECONDS >=20000
),
CATALOG1 AS (
    SELECT 
        C.SIT_SITE_ID, C.CONTENT_TYPE, C.CONTENT_ID, C.TITLE_ADJUSTED AS ORIGINAL_TITLE, C.CONTENT_PROVIDER,
        CAST(REPLACE(C.RUNTIME, ' s', '') AS INT) / 60 AS RUNTIME_MIN,
        CASE WHEN C.CONTENT_TYPE = 'MOVIE' THEN 'MOVIE' ELSE 'SERIE' END AS CATEGORY,
        CAST(RTRIM(c.runtime, 's') AS INT64)/60 AS runtime
    FROM `WHOWNER.LK_MKT_MPLAY_CATALOGUE` C
),
nuevos AS (
    SELECT 
        PL.PLAY_ID, 
        PL.START_PLAY_TIMESTAMP, 
        CAST(PL.CUS_CUST_ID AS STRING) AS CUS_CUST_ID, 
        ROW_NUMBER() OVER(PARTITION BY CUS_CUST_ID ORDER BY START_PLAY_TIMESTAMP ASC) AS ORDER_PLAYS
    FROM `WHOWNER.BT_MKT_MPLAY_PLAYS` AS PL 
    WHERE PL.PLAYBACK_TIME_MILLISECONDS >= 20000 
),
primer_play_ever AS (
    SELECT * FROM nuevos WHERE order_plays = 1
),
PLAYS_DIARIAS_POR_DISPOSITIVO AS (
    SELECT DS, cus_cust_id, CONTENT_ID, SIT_SITE_ID, DEVICE_AJUSTADO, SUM(TOTAL_MIN_VIEWS) as daily_device_tvm
    FROM PLAYS GROUP BY 1, 2, 3, 4, 5
),
PLAYS_DIARIAS_TOTAL_USUARIO AS (
    SELECT DS, cus_cust_id, CONTENT_ID, SIT_SITE_ID, SUM(daily_device_tvm) as total_daily_tvm
    FROM PLAYS_DIARIAS_POR_DISPOSITIVO GROUP BY 1, 2, 3, 4
),
DIA_DE_FINALIZACION AS (
    WITH CUMULATIVE_SUM AS (
        SELECT DS, cus_cust_id, CONTENT_ID, SIT_SITE_ID,
               SUM(total_daily_tvm) OVER (PARTITION BY cus_cust_id, CONTENT_ID, SIT_SITE_ID ORDER BY DS ASC) as cumulative_tvm
        FROM PLAYS_DIARIAS_TOTAL_USUARIO
    )
    SELECT
        Sub.DS as finalization_day, Sub.cus_cust_id, Sub.CONTENT_ID, Sub.SIT_SITE_ID
    FROM (
        SELECT *, LAG(cumulative_tvm, 1, 0) OVER (PARTITION BY cus_cust_id, CONTENT_ID, SIT_SITE_ID ORDER BY DS ASC) as prev_day_cumulative_tvm
        FROM CUMULATIVE_SUM
    ) AS Sub
    JOIN CATALOG1 ON Sub.CONTENT_ID = CATALOG1.CONTENT_ID AND Sub.SIT_SITE_ID = CATALOG1.SIT_SITE_ID
    WHERE Sub.cumulative_tvm >= (CATALOG1.RUNTIME_MIN * 0.9) AND Sub.prev_day_cumulative_tvm < (CATALOG1.RUNTIME_MIN * 0.9)
),
DISPOSITIVO_PRINCIPAL_FINALIZACION AS (
    SELECT 
        DF.cus_cust_id, DF.CONTENT_ID, DF.SIT_SITE_ID,
        FIRST_VALUE(PDP.DEVICE_AJUSTADO) OVER (PARTITION BY DF.cus_cust_id, DF.CONTENT_ID, DF.SIT_SITE_ID ORDER BY PDP.daily_device_tvm DESC) as top_device
    FROM DIA_DE_FINALIZACION DF
    JOIN PLAYS_DIARIAS_POR_DISPOSITIVO PDP ON DF.finalization_day = PDP.DS AND DF.cus_cust_id = PDP.cus_cust_id AND DF.CONTENT_ID = PDP.CONTENT_ID AND DF.SIT_SITE_ID = PDP.SIT_SITE_ID
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DF.cus_cust_id, DF.CONTENT_ID, DF.SIT_SITE_ID ORDER BY PDP.daily_device_tvm DESC) = 1
)
SELECT 
    P.DS AS FECHA,
    P.FECHA_MONTH,
    P.SIT_SITE_ID,
    CASE
        WHEN C.CONTENT_PROVIDER = 'SONY' THEN 'SONY'
        WHEN C.CONTENT_PROVIDER IN ('PARAMOUNT', 'CBS','PARAMOUNTTL','PARAMOUNBR') THEN 'PARAMOUNT'
        WHEN C.CONTENT_PROVIDER = 'MPLAYORIGINALS' THEN 'MPLAYORIGINALS'
        WHEN C.CONTENT_PROVIDER IN ('NBCUAVOD', 'UNIVERSALPLUS') OR P.CHANNEL_ID IN ('3062aa4b18ff46ed8d59fe6c3f088bc6','167e27fd5bb84dfabde7103648b9a96b','3f1cc2cccea34b9490b00d6ac514e225','63b08af757040aebdb2d23246fcf71a','9e95f70f53e54e3b86850c2d9a7b1df5','24d2994c2807438eb89c817534ed76db','bb853ee1e9264f018031baab6ea1e3d2') THEN 'NBCU'
        ELSE C.CONTENT_PROVIDER 
    END AS CP,
    C.ORIGINAL_TITLE,
    C.CATEGORY,
    P.cus_cust_id AS viewers,
    P.DEVICE_AJUSTADO,
    SUM(P.TOTAL_MIN_VIEWS) AS TVM,
    AVG(P.TOTAL_MIN_VIEWS) AS ATV,
    COUNT(DISTINCT P.DS) AS DAYS,
    MAX(CASE WHEN P.PLAY_ID IN (SELECT play_id FROM primer_play_ever) THEN 1 ELSE 0 END) AS NEW_VIEWERS,
    MAX(CASE 
        WHEN P.DS = DF.finalization_day AND P.DEVICE_AJUSTADO = DPF.top_device THEN 1 
        ELSE 0 
    END) AS IS_FINALIZER
FROM PLAYS P
LEFT JOIN CATALOG1 C ON P.CONTENT_ID = C.CONTENT_ID AND P.SIT_SITE_ID = C.SIT_SITE_ID
LEFT JOIN DIA_DE_FINALIZACION DF 
    ON P.cus_cust_id = DF.cus_cust_id 
    AND P.CONTENT_ID = DF.CONTENT_ID 
    AND P.SIT_SITE_ID = DF.SIT_SITE_ID
LEFT JOIN DISPOSITIVO_PRINCIPAL_FINALIZACION DPF
    ON P.cus_cust_id = DPF.cus_cust_id
    AND P.CONTENT_ID = DPF.CONTENT_ID
    AND P.SIT_SITE_ID = DPF.SIT_SITE_ID
GROUP BY
    P.DS,
    P.FECHA_MONTH,
    P.SIT_SITE_ID,
    CP,
    C.ORIGINAL_TITLE,
    C.CATEGORY,
    P.cus_cust_id,
    P.DEVICE_AJUSTADO,
    P.PLAY_ID;