DECLARE start_date DATE DEFAULT DATE '2025-01-01';
DECLARE end_date DATE DEFAULT DATE '2025-07-31';

WITH base AS (
  SELECT
    USER_ID,
    UPPER(DEVICE_PLATFORM) AS DEVICE_PLATFORM,
    START_PLAY_TIMESTAMP,
    DS,
    EXTRACT(HOUR FROM START_PLAY_TIMESTAMP) AS HOUR,
    EXTRACT(DAYOFWEEK FROM DS) AS DAY_NUM,
    FORMAT_DATE('%Y-%m', DS) AS MONTH,
    CASE EXTRACT(DAYOFWEEK FROM DS)
      WHEN 1 THEN 'Domingo'
      WHEN 2 THEN 'Lunes'
      WHEN 3 THEN 'Martes'
      WHEN 4 THEN 'Miércoles'
      WHEN 5 THEN 'Jueves'
      WHEN 6 THEN 'Viernes'
      WHEN 7 THEN 'Sábado'
    END AS DAY_NAME,
    CASE 
      WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN 'TV'
      WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN 'MOBILE'
      ELSE 'OTRO'
    END AS PLATFORM
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE 
    PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND DS BETWEEN start_date AND end_date
    AND (
      UPPER(DEVICE_PLATFORM) LIKE '%TV%'
      OR UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%'
    )
)

SELECT
  DS,
  MONTH,
  DAY_NAME,
  HOUR,
  PLATFORM,
  COUNT(DISTINCT USER_ID) AS USERS
FROM base
WHERE PLATFORM IN ('TV', 'MOBILE')
GROUP BY DS, MONTH, DAY_NAME, HOUR, PLATFORM
ORDER BY DS, PLATFORM, HOUR;
