WITH PUSH_METADATA AS (
  SELECT
      A.CUS_CUST_ID,
      A.EVENT_TYPE,
      B.CAMPAIGN_NAME,
      B.PUSH_TYPE,
      B.STRATEGY
  FROM
      `meli-bi-data.SBOX_MARKETING.BT_OC_PUSH_CUST_EVENT` AS A
  JOIN
      `meli-bi-data.SBOX_MARKETING.LK_OC_METADATA` AS B
  ON
      A.HASH_ID = B.HASH_ID
      AND A.SIT_SITE_ID = B.SIT_SITE_ID
  WHERE
      A.EVENT_TYPE IN ('open', 'test', 'control', 'shown')
),

NEW_RET_RECO AS (
  SELECT
      *,
      DATE_TRUNC(DS,MONTH) AS TIME_FRAME_ID
    , LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC) AS DS_ANT
    , CASE 
        WHEN (LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)) IS NULL THEN 'NEW'
        WHEN DATE_DIFF(DS, (LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)), DAY) <= 30 THEN 'RETAINED'
        WHEN DATE_DIFF(DS, (LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)), DAY) > 30 THEN 'RECOVERED'
        ELSE NULL 
      END AS FLAG_N_R
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE
      PLAYBACK_TIME_MILLISECONDS/1000 >= 20
      AND DS <= CURRENT_DATE() - 1
),

PLAYS_SEGMENTED AS (
  SELECT
      SIT_SITE_ID,
      USER_ID,
      CUS_CUST_ID,
      TIME_FRAME_ID,
      FLAG_N_R
  FROM NEW_RET_RECO
  QUALIFY 
    ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, USER_ID, TIME_FRAME_ID ORDER BY START_PLAY_TIMESTAMP ASC) = 1
)

SELECT
    P.CAMPAIGN_NAME,
    P.PUSH_TYPE,
    P.STRATEGY,
    PS.FLAG_N_R,
    COUNT(DISTINCT P.CUS_CUST_ID) AS cantidad_usuarios_en_campana
FROM PUSH_METADATA AS P
LEFT JOIN PLAYS_SEGMENTED AS PS
ON P.CUS_CUST_ID = PS.CUS_CUST_ID
GROUP BY
    P.CAMPAIGN_NAME,
    P.PUSH_TYPE,
    P.STRATEGY,
    PS.FLAG_N_R
ORDER BY
    P.CAMPAIGN_NAME,
    PS.FLAG_N_R;