DECLARE FECHA_FROM DATE;

DELETE FROM `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS`
WHERE FECHA_CONV BETWEEN CURRENT_DATE-8 AND CURRENT_DATE;

SET FECHA_FROM = (SELECT MAX(FECHA_CONV) FROM  `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS`) + 1;

INSERT INTO  `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS` (
  WITH CONV AS (
    SELECT 
      *
      FROM (
        SELECT
          P.USER_ID,
          P.SIT_SITE_ID,
          P.DS AS FECHA_CONV,
          DEVICE_PLATFORM
        FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
        WHERE P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
        QUALIFY ROW_NUMBER()OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY P.START_PLAY_TIMESTAMP ASC) = 1
      )
    WHERE FECHA_CONV BETWEEN FECHA_FROM AND CURRENT_DATE-1
  ),
  ATT_ORIGINS AS (
    SELECT DISTINCT
      C.USER_ID,
      C.SIT_SITE_ID,
      C.FECHA_CONV,
      C.DEVICE_PLATFORM,
      S.ORIGIN_PATH,
      S.DS AS FECHA_ESTIMULOS,
      DATE_DIFF(FECHA_CONV,S.DS,DAY) AS DIAS_TO_CONV      
    FROM CONV AS C
    LEFT JOIN  `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS S 
      ON S.USER_ID = C.USER_ID
      AND S.SIT_SITE_ID = C.SIT_SITE_ID
      AND S.DS BETWEEN C.FECHA_CONV-29 AND C.FECHA_CONV
      AND S.DS >= FECHA_FROM-5-30
  ),
  BASE_CALCULOS AS (
  SELECT 
    *,
    dense_rank()OVER(PARTITION BY USER_ID,SIT_SITE_ID ORDER BY DIAS_TO_CONV DESC) AS ORDER_DESC_TIME --> USAMOS DENSE PARA PONERLE EL MISMO PESO AL DIA
  FROM ATT_ORIGINS
  )
  SELECT 
    *,
    POW(2,ORDER_DESC_TIME)/(SUM(POW(2,ORDER_DESC_TIME))OVER(PARTITION BY USER_ID,SIT_SITE_ID)) AS CONVERTION_W,
    0 AS RET_1_30,
    0 AS RET_31_60,
    0 AS AHA_MOMENT,
  FROM BASE_CALCULOS
);

CREATE OR REPLACE TABLE `meli-sbox.MPLAY.MPLAY_NEGOCIO_ADQUITSTION_METRICS` AS (
  WITH SOURCE_CONVERTION AS (
    SELECT
      SIT_SITE_ID,
      COALESCE(ORIGIN_PATH,'NULO') AS ORIGIN_PATH,
      FECHA_ESTIMULOS,
      SUM(CONVERTION_W) AS CONVERTIONS
    FROM `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS`
    GROUP BY ALL
  ),
  TOTAL_SOURCE_TRAFICO AS (
    SELECT
      COALESCE(S.ORIGIN_PATH,'NULO') AS ORIGIN_PATH,
      S.DS AS FECHA_ESTIMULOS,
      S.SIT_SITE_ID,
      COUNT(DISTINCT S.USER_ID) AS TOTAL_TRAFICO,
      COUNT(DISTINCT CASE WHEN ((HAS_SEARCH IS TRUE OR HAS_VCP IS TRUE OR HAS_PLAY IS TRUE OR HAS_VCM IS TRUE) OR TOTAL_FEED_IMPRESSIONS > 1) THEN S.USER_ID ELSE NULL END) AS TOTAL_TRAFICO_VISITOR,
    FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS S
    LEFT JOIN
      ( SELECT DISTINCT
        USER_ID,
        SIT_SITE_ID,
        FECHA_CONV
      FROM `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS`) AS C 
        ON C.USER_ID = S.USER_ID
        AND C.SIT_SITE_ID = S.SIT_SITE_ID
        AND C.FECHA_CONV < S.DS
    WHERE C.USER_ID IS NULL
    GROUP BY ALL
  )

  SELECT
  --SC.DEVICE_PLATFORM AS PLATFORM_CONVERTION,
    COALESCE(OM.SOURCE_SESSION_L1,'NULO') AS NEGOCIO,
    COALESCE(OM.TEAM,'NULO') AS TEAM,
    COALESCE(OM.SOURCE_SESSION_L2,'NULO') AS ORIGIN_PATH,
    S.FECHA_ESTIMULOS,
    S.SIT_SITE_ID,
    S.TOTAL_TRAFICO,
    S.TOTAL_TRAFICO_VISITOR,
    SC.CONVERTIONS
  FROM TOTAL_SOURCE_TRAFICO AS S
  LEFT JOIN SOURCE_CONVERTION AS SC 
    ON SC.SIT_SITE_ID = S.SIT_SITE_ID
    AND SC.ORIGIN_PATH = S.ORIGIN_PATH
    AND SC.FECHA_ESTIMULOS = S.FECHA_ESTIMULOS
  LEFT JOIN `meli-sbox.MPLAY.LK_MPLAY_SOURCE_TYPE_ORIGIN_SESSION` AS OM   
    ON OM.SOURCE_TYPE = S.ORIGIN_PATH
);

CREATE OR REPLACE TABLE `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS` AS (
  SELECT
    USER_ID,
    SIT_SITE_ID,
    FECHA_CONV,
    DEVICE_PLATFORM,
    ORIGIN_PATH,
    FECHA_ESTIMULOS,
    DIAS_TO_CONV,
    ORDER_DESC_TIME,
    CONVERTION_W,
    (
      SELECT MAX(CASE WHEN P.USER_ID IS NOT NULL THEN 1 ELSE 0 END)
      FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
      WHERE P.USER_ID = A.USER_ID
        AND P.SIT_SITE_ID = A.SIT_SITE_ID
        AND P.DS BETWEEN A.FECHA_CONV +1 AND A.FECHA_CONV+30
        AND P.PLAYBACK_TIME_MILLISECONDS/1000>=20
    ) AS RET_1_30,
    (
      SELECT MAX(CASE WHEN P.USER_ID IS NOT NULL THEN 1 ELSE 0 END)
      FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
      WHERE P.USER_ID = A.USER_ID
        AND P.SIT_SITE_ID = A.SIT_SITE_ID
        AND P.DS BETWEEN A.FECHA_CONV + 31 AND A.FECHA_CONV + 61
        AND P.PLAYBACK_TIME_MILLISECONDS/1000>=20) AS RET_31_60,
    (
      SELECT CASE WHEN COUNT(DISTINCT P.DS) >= 3 THEN 1 ELSE 0 END
      FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
      WHERE P.USER_ID = A.USER_ID
        AND P.SIT_SITE_ID = A.SIT_SITE_ID
        AND P.DS BETWEEN A.FECHA_CONV AND A.FECHA_CONV + 29
        AND P.PLAYBACK_TIME_MILLISECONDS/1000>=20) AS AHA_MOMENT
  FROM `meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_NEW_USERS` AS A);

CREATE OR REPLACE TABLE meli-sbox.MPLAY.MPLAY_NEGOCIO_COHORTS_DASH AS (
  WITH PLAY_DAYS AS (
    SELECT DISTINCT
      P.SIT_SITE_ID AS SIT_SITE_ID,
      (P.USER_ID) AS USER_ID,
      (P.DS) AS DAY_PLAY,
      SUM(P.PLAYBACK_TIME_MILLISECONDS/60000) AS PLAYBACK_TIME,
    FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` as P
    WHERE P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
    GROUP BY ALL
  ),
  PLAY_FIRST_DAY AS (
    SELECT
      SIT_SITE_ID,
      USER_ID,
      MIN(DAY_PLAY) AS FIRST_DAY
    FROM PLAY_DAYS
    GROUP BY ALL
  ),
  TABLE_CALENDAR AS (
    SELECT
      *
    FROM (
      SELECT
        *,
        ROW_NUMBER()OVER(PARTITION BY FECHA_COHORT ORDER BY FECHA_INI ASC) AS MONTH_NUMBER
      FROM (
        SELECT
          T.TIM_DAY AS FECHA_COHORT,
          T2.TIM_DAY -29 AS FECHA_INI,
          T2.TIM_DAY AS FECHA_FIN,
        FROM `meli-bi-data.WHOWNER.LK_TIM_DAYS` AS T
        LEFT JOIN `meli-bi-data.WHOWNER.LK_TIM_DAYS` AS T2 ON T.TIM_DAY+1 <= T2.TIM_DAY
      --> +1 PARA SACAR DIA DE ALTA
        WHERE T.TIM_DAY >= DATE'2023-07-01'
        QUALIFY MOD(ROW_NUMBER()OVER(PARTITION BY T.TIM_DAY ORDER BY T2.TIM_DAY ASC), 30) = 0
      ) AS A
      WHERE FECHA_FIN <= DATE_TRUNC(CURRENT_DATE-1,MONTH)-1
      ) AS B
    QUALIFY COUNT(FECHA_FIN)OVER (PARTITION BY DATE_TRUNC(FECHA_COHORT,MONTH),MONTH_NUMBER) = EXTRACT(DAY FROM(LAST_DAY(FECHA_COHORT)))
  --> COHORT_HASTA AYER
  ),
  USERS_CALENDAR AS (
    SELECT
      PF.*,
      T.FECHA_INI,
      T.FECHA_FIN,
      MONTH_NUMBER
    FROM PLAY_FIRST_DAY AS PF
    LEFT JOIN TABLE_CALENDAR AS T ON PF.FIRST_DAY = T.FECHA_COHORT
  ) ,
  BASE AS (
    SELECT
      *,
      CASE WHEN FLAG_TVM > 0 AND
      ROW_NUMBER()OVER(PARTITION BY SIT_SITE_ID,USER_ID,FLAG_TVM ORDER BY MONTH_NUMBER ASC) = MONTH_NUMBER THEN 'ALL_MONTH' ELSE 'NOT_RECURRENT' END AS FLAG_CONSEC,
      COUNT(DISTINCT USER_ID || SIT_SITE_ID) OVER(PARTITION BY MONTH_COHORT_ACQ,SIT_SITE_ID) AS TOTAL_USERS_COHORT
    FROM (
      SELECT
        U.USER_ID,
        U.SIT_SITE_ID,
        U.MONTH_NUMBER,
        DATE_TRUNC(U.FIRST_DAY,MONTH) AS MONTH_COHORT_ACQ,
        SUM(PLAYBACK_TIME) AS TVM,
        CASE WHEN SUM(PLAYBACK_TIME)>0 THEN 1 ELSE 0 END AS FLAG_TVM
      FROM USERS_CALENDAR AS U
      LEFT JOIN PLAY_DAYS AS P 
        ON U.USER_ID = P.USER_ID
        AND U.SIT_SITE_ID = P.SIT_SITE_ID
        AND P.DAY_PLAY BETWEEN U.FECHA_INI AND U.FECHA_FIN
      GROUP BY ALL
    )
  )

  SELECT
    SIT_SITE_ID,
    MONTH_COHORT_ACQ,
    MONTH_NUMBER-1 AS MONTH_RETENTION,
    TOTAL_USERS_COHORT AS TOTAL_USERS_COHORT,
    COUNT(DISTINCT CASE WHEN TVM > 0 THEN USER_ID||SIT_SITE_ID ELSE NULL END) AS TOTAL_USERS_RETENTION,
    SUM(TVM) AS TVM,
    COUNT(DISTINCT CASE WHEN TVM > 0 AND FLAG_CONSEC = 'ALL_MONTH' THEN USER_ID||SIT_SITE_ID ELSE NULL END) AS ALL_MONTH_USER_RET,
    SUM( CASE WHEN TVM > 0 AND FLAG_CONSEC = 'ALL_MONTH' THEN TVM ELSE NULL END) AS ALL_MONTH_TVM
  FROM BASE
  WHERE MONTH_NUMBER IS NOT NULL
  GROUP BY ALL
); --> AHA_MOMENT_ATTRIBUTION

CREATE OR REPLACE TABLE meli-sbox.MPLAY.MPLAY_NEGOCIO_ATT_AHA_MOMENT_USERS AS (
  WITH CONV AS (
    SELECT
      A.USER_ID,
      A.SIT_SITE_ID,
      A.DS AS FECHA_CUMPLE_AHA,
      A.FIRST_DS_USER,
      A.DEVICE_PLATFORM
    FROM (
      SELECT DISTINCT
        P.USER_ID,
        P.SIT_SITE_ID,
        P.DS,
        MIN(DS) OVER (PARTITION BY SIT_SITE_ID,USER_ID) AS FIRST_DS_USER,
        FIRST_VALUE(DEVICE_PLATFORM)OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY START_PLAY_TIMESTAMP ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS DEVICE_PLATFORM,
      FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
      WHERE P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
      ) AS A
    WHERE A.DS BETWEEN FIRST_DS_USER AND FIRST_DS_USER+29 --> PRIMEROS 30 DIAS
    QUALIFY ROW_NUMBER()OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY DS ASC ) = 3 --> LLEGO A 3 DIAS
  ),
  ATT_ORIGINS AS (
    SELECT DISTINCT
      C.USER_ID,
      C.SIT_SITE_ID,
      C.FIRST_DS_USER,
      C.FECHA_CUMPLE_AHA,
      C.DEVICE_PLATFORM,
      S.ORIGIN_PATH,
      S.DS AS FECHA_ESTIMULOS,
      DATE_DIFF(C.FECHA_CUMPLE_AHA,S.DS,DAY) AS DIAS_TO_CONV
    FROM CONV AS C
    LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS S 
      ON S.USER_ID = C.USER_ID
      AND S.SIT_SITE_ID = C.SIT_SITE_ID
      AND S.DS BETWEEN C.FIRST_DS_USER AND C.FECHA_CUMPLE_AHA
      -- AND S.DS >= FECHA_FROM-5-30
  ),
  BASE_CALCULOS AS (
    SELECT
      *,
      dense_rank()OVER(PARTITION BY USER_ID,SIT_SITE_ID ORDER BY DIAS_TO_CONV DESC) AS ORDER_DESC_TIME --> USAMOS DENSE PARA PONERLE EL MISMO PESO AL DIA
    FROM ATT_ORIGINS
  )
  SELECT
    *,
    POW(2,ORDER_DESC_TIME)/(SUM(POW(2,ORDER_DESC_TIME))OVER(PARTITION BY USER_ID,SIT_SITE_ID)) AS CONVERTION_W
  FROM BASE_CALCULOS
)
