DELETE FROM `meli-sbox.MPLAY.MPLAY_NEGOCIO_SEARCH_WORDS`
WHERE DS >= CURRENT_DATE-7 
;
INSERT INTO `meli-sbox.MPLAY.MPLAY_NEGOCIO_SEARCH_WORDS`
(
select 
site AS SIT_SITE_ID,
DS,
TRIM(UPPER(JSON_VALUE(EVENT_DATA, '$.query'))) AS WORD,
count(*) AS TOTAL_TRACKS
from `meli-bi-data.MELIDATA.TRACKS`
WHERE DS >= CURRENT_DATE-7
AND PATH = '/mercadoplay/search'
group by ALL )