DECLARE date_from DATE;
DECLARE date_to DATE;
SET date_from = '2025-04-01';
SET date_to = CURRENT_DATE - 1;

WITH ALL_TV_SESSIONS AS (
  SELECT
    S.SIT_SITE_ID,
    S.USER_ID,
    S.DS,
    DATE_TRUNC(S.DS, MONTH) AS MONTH_ID, 
    S.SESSION_ID AS TV_SESSION_ID,
    S.START_TIME_USERTIMESTAMP AS TV_SESSION_START_TIMESTAMP
  FROM meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION AS s
  WHERE S.DS >= date_from
    AND S.DS <= date_to
    AND UPPER(S.DEVICE_PLATFORM) LIKE '%TV%'
    and safe_cast(user_id as int64) is not null
    AND IS_BOUNCED IS FALSE
),
TV_SESSIONS_PRECEDED_BY_MOBILE AS (
  SELECT DISTINCT
    TV.SIT_SITE_ID,
    TV.USER_ID,
    TV.MONTH_ID,
    TV.DS,
    TV.TV_SESSION_ID
  FROM ALL_TV_SESSIONS AS TV
  INNER JOIN meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION AS S_MOBILE
    ON TV.USER_ID = S_MOBILE.USER_ID
    AND TV.SIT_SITE_ID = S_MOBILE.SIT_SITE_ID
    AND S_MOBILE.DS >= DATE_SUB(TV.DS, INTERVAL 7 DAY)
AND S_MOBILE.DS <= TV.DS
  WHERE
    UPPER(S_MOBILE.DEVICE_PLATFORM) LIKE '%MOBILE%'
    AND S_MOBILE.END_TIME_USERTIMESTAMP < TV.TV_SESSION_START_TIMESTAMP
    and safe_cast(S_MOBILE.user_id as int64) is not null
    AND IS_BOUNCED IS FALSE
),
TOTAL_TV_VISITORS_MONTH_SITE AS (
  SELECT
    SIT_SITE_ID,
    MONTH_ID,
    COUNT(DISTINCT USER_ID) AS TOTAL_TV_VISITORS
  FROM ALL_TV_SESSIONS
  GROUP BY ALL
),
INFLUENCED_VISITORS_MONTH_SITE AS (
  SELECT
    SIT_SITE_ID,
    MONTH_ID,
    COUNT(DISTINCT USER_ID) AS INFLUENCED_TV_VISITORS
  FROM TV_SESSIONS_PRECEDED_BY_MOBILE
  GROUP BY ALL
),
TOTAL_TV_VISITORS AS (
      SELECT
    S.SIT_SITE_ID,
    S.USER_ID,
    S.DS,
    DATE_TRUNC(S.DS, MONTH) AS MONTH_ID, 
    S.SESSION_ID AS TV_SESSION_ID,
    S.START_TIME_USERTIMESTAMP AS TV_SESSION_START_TIMESTAMP
  FROM meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION AS s
  WHERE S.DS >= '2025-04-01'
    AND S.DS <= '2025-12-31'
    AND UPPER(S.DEVICE_PLATFORM) LIKE '%TV%'
    /* and safe_cast(user_id as int64) is not null */
    AND IS_BOUNCED IS FALSE
),
TOTAL_MOBILE_VISITORS AS (
      SELECT
    S.SIT_SITE_ID,
    S.USER_ID,
    S.DS,
    DATE_TRUNC(S.DS, MONTH) AS MONTH_ID, 
    S.SESSION_ID AS TV_SESSION_ID,
    S.START_TIME_USERTIMESTAMP AS TV_SESSION_START_TIMESTAMP
  FROM meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION AS s
  WHERE S.DS >= '2025-04-01'
    AND S.DS <= '2025-12-31'
    AND UPPER(S.DEVICE_PLATFORM) LIKE '%MOBILE%'
    /* and safe_cast(user_id as int64) is not null */
    AND IS_BOUNCED IS FALSE
)

SELECT
  INF.MONTH_ID,
  SUM(INF.INFLUENCED_TV_VISITORS) AS TOTAL_TV_VISITORS_PRECEDED_BY_MOBILE,
  SUM(TD.TOTAL_TV_VISITORS) AS GRAND_TOTAL_TV_VISITORS,
  ROUND(SAFE_DIVIDE(SUM(INF.INFLUENCED_TV_VISITORS), SUM(TD.TOTAL_TV_VISITORS)), 3) AS MOBILE_TO_TV_SESSION_VISITORS,
  COUNT(DISTINCT TMV.USER_ID) AS TOTAL_MOBILE_VISITORS,
  COUNT(DISTINCT TTV.USER_ID) AS TOTAL_TV_VISITORS_OVERALL,
  ROUND(SAFE_DIVIDE(SUM(INF.INFLUENCED_TV_VISITORS), SUM(TD.TOTAL_TV_VISITORS)), 3) * COUNT(DISTINCT TTV.USER_ID) AS MOBILE_EXTRAPOLADO,
  SAFE_DIVIDE(ROUND(SAFE_DIVIDE(SUM(INF.INFLUENCED_TV_VISITORS), SUM(TD.TOTAL_TV_VISITORS)), 3) * COUNT(DISTINCT TTV.USER_ID),COUNT(DISTINCT TMV.USER_ID)) AS RATIO_MOBILE_TO_TV_EXTRAPOLATED
FROM INFLUENCED_VISITORS_MONTH_SITE AS INF
INNER JOIN TOTAL_TV_VISITORS_MONTH_SITE AS TD
  ON INF.SIT_SITE_ID = TD.SIT_SITE_ID
  AND INF.MONTH_ID = TD.MONTH_ID
LEFT JOIN TOTAL_MOBILE_VISITORS AS TMV
  ON INF.MONTH_ID = TMV.MONTH_ID
  AND INF.SIT_SITE_ID = TMV.SIT_SITE_ID
LEFT JOIN TOTAL_TV_VISITORS AS TTV
  ON INF.MONTH_ID = TTV.MONTH_ID
  AND INF.SIT_SITE_ID = TTV.SIT_SITE_ID
GROUP BY 1
ORDER BY 1;

