INSERT INTO `meli-sbox.MPLAY.MPLAY_BEHAVIOUR_PLATFORM` (
    TIMEFRAME_TYPE,
    TIMEFRAME_ID,
    FOCUSED, 
    SIT_SITE_ID, 
    PLATFORM_OPEN,
    PLATFORM_ORIGIN, 
    FLAG_LOG,
    CUST_TYPE,
    TVM_TIMEFRAME,
    MIGRATION_FLOW_DESTINATION,
    TOTAL_USERS,
    TVM_TIMEFRAME_DESTINATION
)
WITH BASE_LAG AS (
    -- =========================
    -- MONTHLY
    -- =========================
    SELECT
        *,
        'MONTHLY' AS TIMEFRAME_TYPE,
        DATE_TRUNC(DS, MONTH) AS TIMEFRAME_ID,
        LAG(DS) OVER (
            PARTITION BY SIT_SITE_ID, USER_ID
            ORDER BY START_PLAY_TIMESTAMP
        ) AS DS_ANT
    FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
    WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
      AND DS <= CURRENT_DATE - 1
),

FLAGGED AS (
    SELECT
        *,
        CASE
            WHEN DS_ANT IS NULL THEN 'NEW'
            WHEN DATE_DIFF(DS, DS_ANT, DAY) <= 30 THEN 'RETAINED'
            ELSE 'RECOVERED'
        END AS FLAG_N_R
    FROM BASE_LAG
),

USER_TF_FLAG AS (
    SELECT
        SIT_SITE_ID,
        USER_ID,
        TIMEFRAME_TYPE,
        TIMEFRAME_ID,
        ARRAY_AGG(FLAG_N_R ORDER BY START_PLAY_TIMESTAMP LIMIT 1)[OFFSET(0)]
            AS FLAG_N_R_FINAL
    FROM FLAGGED
    GROUP BY SIT_SITE_ID, USER_ID, TIMEFRAME_TYPE, TIMEFRAME_ID
),

RESUMEN_USER_TF AS (
    SELECT
        F.SIT_SITE_ID,
        F.USER_ID,
        F.TIMEFRAME_TYPE,
        F.TIMEFRAME_ID,
        U.FLAG_N_R_FINAL,
        SUM(F.PLAYBACK_TIME_MILLISECONDS) / 60000 AS TVM_TOTAL_TIMEFRAME,
        SUM(IF(UPPER(F.DEVICE_PLATFORM) LIKE '%TV%',
               F.PLAYBACK_TIME_MILLISECONDS, 0)) / 60000 AS TOTAL_TV,
        SUM(IF(UPPER(F.DEVICE_PLATFORM) LIKE '%MOBILE%',
               F.PLAYBACK_TIME_MILLISECONDS, 0)) / 60000 AS TOTAL_MOBILE,
        SUM(IF(UPPER(F.DEVICE_PLATFORM) LIKE '%DESK%',
               F.PLAYBACK_TIME_MILLISECONDS, 0)) / 60000 AS TOTAL_DESKTOP,
        SUM(IF(F.PLAYBACK_TIME_MILLISECONDS_CAST / 1000 >= 20,
               F.PLAYBACK_TIME_MILLISECONDS_CAST, 0)) / 60000 AS TOTAL_CAST
    FROM FLAGGED F
    JOIN USER_TF_FLAG U
      USING (SIT_SITE_ID, USER_ID, TIMEFRAME_TYPE, TIMEFRAME_ID)
    GROUP BY ALL
),

BASE_PLATFORM AS (
    SELECT
        USER_ID,
        SIT_SITE_ID,
        TIMEFRAME_TYPE,
        TIMEFRAME_ID,
        FLAG_N_R_FINAL AS CUST_TYPE,
        TVM_TOTAL_TIMEFRAME,
        CASE
            WHEN ROUND(TVM_TOTAL_TIMEFRAME, 2) = ROUND(TOTAL_CAST, 2)
                 AND TOTAL_CAST > 0 THEN 'CAST'
            ELSE CONCAT(
                IF(TOTAL_TV > 0, 'SMART', ''),
                IF(TOTAL_MOBILE > 0, 'MOBILE', ''),
                IF(TOTAL_DESKTOP > 0, 'DESKTOP', ''),
                IF(TOTAL_CAST > 0, 'CAST', '')
            )
        END AS PLATFORM
    FROM RESUMEN_USER_TF
    WHERE TIMEFRAME_ID IN (
        DATE_TRUNC(DATE_SUB(CURRENT_DATE, INTERVAL 2 MONTH), MONTH), 
        DATE_TRUNC(DATE_SUB(CURRENT_DATE, INTERVAL 1 MONTH), MONTH))
),

BASE_PLATFORM_2 AS (
    SELECT
        *,
        CASE
            WHEN PLATFORM = 'SMART' THEN 'SMART'
            WHEN PLATFORM = 'MOBILE' THEN 'MOBILE'
            WHEN PLATFORM = 'CAST' THEN 'CAST'
            WHEN PLATFORM = 'DESKTOP' THEN 'DESKTOP'
            WHEN PLATFORM = 'DESKTOPCAST' THEN 'DESKTOP + TV'
            WHEN PLATFORM = 'MOBILECAST' THEN 'MOBILE + TV'
            WHEN PLATFORM = 'MOBILEDESKTOP' THEN 'MOBILE + DESKTOP'
            WHEN PLATFORM = 'MOBILEDESKTOPCAST' THEN 'MOBILE + DESKTOP + TV'
            WHEN PLATFORM = 'SMARTDESKTOP' THEN 'DESKTOP + TV'
            WHEN PLATFORM = 'SMARTDESKTOPCAST' THEN 'DESKTOP + TV'
            WHEN PLATFORM = 'SMARTMOBILE' THEN 'MOBILE + TV'
            WHEN PLATFORM = 'SMARTMOBILECAST' THEN 'MOBILE + TV'
            WHEN PLATFORM = 'SMARTMOBILEDESKTOP' THEN 'MOBILE + DESKTOP + TV'
            WHEN PLATFORM = 'SMARTMOBILEDESKTOPCAST' THEN 'MOBILE + DESKTOP + TV'
            ELSE 'OTHER'
        END AS PLATFORM_OPEN,

        CASE
            WHEN LEFT(PLATFORM, 5) = 'SMART' AND LENGTH(PLATFORM) > 5 THEN 'MULTI W/SMART'
            WHEN PLATFORM = 'SMART' THEN 'SMART'
            WHEN PLATFORM = 'MOBILE' THEN 'MOBILE'
            WHEN PLATFORM = 'DESKTOP' THEN 'DESKTOP'
            WHEN PLATFORM = 'CAST' THEN 'CAST'
            WHEN PLATFORM LIKE '%CAST%' THEN 'MULTI W/SMART'
            ELSE 'MULTI OTHERS'
        END AS PLATFORM_SMART,

        CASE
            WHEN PLATFORM LIKE '%MOBILE%' AND LENGTH(PLATFORM) > 6 THEN 'MULTI W/MOBILE'
            WHEN PLATFORM IN ('SMART','MOBILE','DESKTOP','CAST') THEN PLATFORM
            ELSE 'MULTI OTHERS'
        END AS PLATFORM_MOBILE,

        CASE
            WHEN PLATFORM LIKE '%DESKTOP%' AND LENGTH(PLATFORM) > 7 THEN 'MULTI W/DESKTOP'
            WHEN PLATFORM IN ('SMART','MOBILE','DESKTOP','CAST') THEN PLATFORM
            ELSE 'MULTI OTHERS'
        END AS PLATFORM_DESKTOP,

        IF(SAFE_CAST(USER_ID AS INT64) IS NOT NULL, 'LOG', 'NOT_LOG') AS FLAG_LOG
    FROM BASE_PLATFORM
),

BASE_PLATFORM_EXPLODED AS (
    SELECT
        USER_ID,
        SIT_SITE_ID,
        TIMEFRAME_TYPE,
        TIMEFRAME_ID,
        CUST_TYPE,
        TVM_TOTAL_TIMEFRAME,
        FLAG_LOG,
        PLATFORM_OPEN,
        platform_type AS APERTURA,
        platform_value
    FROM BASE_PLATFORM_2
    CROSS JOIN UNNEST([
        STRUCT('SMART' AS platform_type, PLATFORM_SMART AS platform_value),
        STRUCT('MOBILE', PLATFORM_MOBILE),
        STRUCT('DESKTOP', PLATFORM_DESKTOP)
    ])
),

MIGRATION AS (
    SELECT
        A.TIMEFRAME_TYPE,
        A.TIMEFRAME_ID,
        A.APERTURA,
        A.SIT_SITE_ID,
        COALESCE(B.PLATFORM_OPEN, 'CHURNED') AS PLATFORM_OPEN_DESTINO,
        A.platform_value AS PLATFORM_ORIGIN,
        A.FLAG_LOG,
        A.CUST_TYPE,
        CASE
            WHEN A.TVM_TOTAL_TIMEFRAME < 3 THEN 'A. MENOR A 3 MIN'
            WHEN A.TVM_TOTAL_TIMEFRAME < 10 THEN 'B. ENTRE 3 Y 10 MIN'
            WHEN A.TVM_TOTAL_TIMEFRAME < 30 THEN 'C. ENTRE 10 Y 30 MIN'
            ELSE 'D. MAYOR A 30 MIN'
        END AS TVM_TIMEFRAME,
        CASE
            WHEN B.platform_value IS NULL THEN 'CHURNED'
            WHEN A.platform_value = B.platform_value THEN 'RETAINED SAME PLATFORM'
            ELSE B.platform_value
        END AS MIGRATION_FLOW_DESTINATION,
        A.USER_ID,
        B.TVM_TIMEFRAME AS TVM_TIMEFRAME_DESTINATION
    FROM BASE_PLATFORM_EXPLODED A
    LEFT JOIN BASE_PLATFORM_EXPLODED B
      ON A.USER_ID = B.USER_ID
     AND A.SIT_SITE_ID = B.SIT_SITE_ID
     AND A.APERTURA = B.APERTURA
     AND A.TIMEFRAME_TYPE = B.TIMEFRAME_TYPE
     AND B.TIMEFRAME_ID = CASE
            WHEN A.TIMEFRAME_TYPE = 'MONTHLY'
                THEN DATE_ADD(A.TIMEFRAME_ID, INTERVAL 1 MONTH)
            ELSE DATE_ADD(A.TIMEFRAME_ID, INTERVAL 1 WEEK)
        END
)

SELECT
    TIMEFRAME_TYPE,
    TIMEFRAME_ID,
    APERTURA AS FOCUSED, -- Aquí mapeamos APERTURA a la columna FOCUSED
    SIT_SITE_ID,
    PLATFORM_OPEN_DESTINO,
    PLATFORM_ORIGIN AS PLATFORM_ORIGIN, -- Aquí mapeamos PLATFORM_ORIGIN a PLATFORM_ORIGIN
    FLAG_LOG,
    CUST_TYPE,
    TVM_TIMEFRAME,
    MIGRATION_FLOW_DESTINATION,
    COUNT(DISTINCT USER_ID) AS TOTAL_USERS,
    TVM_TIMEFRAME_DESTINATION
FROM MIGRATION
GROUP BY ALL