-- description: Análisis de migración semanal de usuarios entre plataformas de consumo, segmentado por recurrencia y nivel de consumo
-- domain: behaviour
-- product: mplay
-- use_case: migration_analysis
-- grain: week_id, site, platform_origin, migration_flow_destination, cust_type, tvm_timeframe, flag_log
-- time_grain: weekly
-- date_column: DS
-- date_filter: up_to (hasta current_date - 1, con análisis desde 2025-01-01)
-- threshold_rule: playback_time >= 20s
-- metrics:
-- - TOTAL_USERS: usuarios únicos que migran, retienen plataforma o churnean entre semanas consecutivas
-- dimensions:
-- - PLATFORM_ORIGIN: plataforma principal del usuario en la semana origen
-- - MIGRATION_FLOW_DESTINATION: destino de plataforma en W+1 (misma plataforma, otra plataforma o churn)
-- - CUST_TYPE: clasificación de recurrencia (NEW, RETAINED, RECOVERED)
-- - TVM_TIMEFRAME: bucket de minutos consumidos en la semana origen
-- - FLAG_LOG: indicador de usuario logueado
-- tables_read:
-- - WHOWNER.BT_MKT_MPLAY_PLAYS
-- joins:
-- - Derivación interna por USER_ID, SIT_SITE_ID y WEEK_ID (self join para W vs W+1)
-- owner: data_team

WITH NEW_RET_RECO AS
(
    SELECT
        *
    , DATE_TRUNC(DS, WEEK(MONDAY)) AS TIME_FRAME_ID
    , LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC) AS DS_ANT
    , (CASE WHEN (LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)) IS NULL THEN 'NEW'
            WHEN DATE_DIFF(DS, (LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)), DAY) <= 30 THEN 'RETAINED'
            WHEN DATE_DIFF(DS, (LAG(DS, 1) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)), DAY) > 30 THEN 'RECOVERED'
            ELSE NULL END) AS FLAG_N_R
    FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
    WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20
    AND DS <= CURRENT_DATE - 1
),
ATTR_TIME_FRAME_ELEGIDO AS (
    SELECT
        SIT_SITE_ID,
        USER_ID,
        TIME_FRAME_ID,
        FLAG_N_R
    FROM NEW_RET_RECO
    QUALIFY ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, USER_ID, TIME_FRAME_ID ORDER BY START_PLAY_TIMESTAMP ASC) = 1
),
CRUCE_FLAG AS (
    SELECT
        A.*,
        E.FLAG_N_R AS FLAG_N_R_FINAL
    FROM NEW_RET_RECO AS A
    INNER JOIN ATTR_TIME_FRAME_ELEGIDO AS E ON E.SIT_SITE_ID = A.SIT_SITE_ID AND E.USER_ID = A.USER_ID AND E.TIME_FRAME_ID = A.TIME_FRAME_ID
),
RESUMEN_USER_TF AS (
    SELECT
        SIT_SITE_ID,
        USER_ID,
        TIME_FRAME_ID AS WEEK_ID,
        FLAG_N_R_FINAL,
        SUM(PLAYBACK_TIME_MILLISECONDS/60000) AS TVM_TOTAL_TIMEFRAME,
        SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_TV,
        SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_MOBILE,
        SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_DESKTOP,
        SUM(CASE WHEN PLAYBACK_TIME_MILLISECONDS_CAST/1000 >= 20 THEN PLAYBACK_TIME_MILLISECONDS_CAST/60000 ELSE 0 END) AS TOTAL_CAST
    FROM CRUCE_FLAG
    GROUP BY ALL
),
BASE_PLATFORM AS (
    SELECT
        USER_ID,
        SIT_SITE_ID,
        WEEK_ID,
        FLAG_N_R_FINAL AS CUST_TYPE,
        TVM_TOTAL_TIMEFRAME,
        CASE
            WHEN ROUND(TVM_TOTAL_TIMEFRAME, 2) = ROUND(TOTAL_CAST, 2) AND TOTAL_CAST > 0 THEN 'CAST'
            ELSE CONCAT(
                CASE WHEN TOTAL_TV > 0 THEN 'SMART' ELSE '' END ,'',
                CASE WHEN TOTAL_MOBILE > 0 THEN 'MOBILE' ELSE '' END ,'',
                CASE WHEN TOTAL_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END ,'',
                CASE WHEN TOTAL_CAST > 0 THEN 'CAST' ELSE '' END
            )
        END AS PLATFORM
    FROM  RESUMEN_USER_TF
    WHERE WEEK_ID >= '2025-01-01'
    GROUP BY ALL
),
BASE_PLATFORM_2 AS (
    SELECT
        BP.USER_ID,
        BP.WEEK_ID,
        BP.CUST_TYPE,
        BP.TVM_TOTAL_TIMEFRAME,
        BP.PLATFORM,
        BP.SIT_SITE_ID,
        CASE
             WHEN LEFT(BP.PLATFORM, 5) = 'SMART' AND LENGTH(BP.PLATFORM) > 5 THEN 'MULTI W/SMART'
            WHEN BP.PLATFORM = 'SMART' THEN 'SMART'
            WHEN BP.PLATFORM = 'MOBILE' THEN 'MOBILE'
            WHEN BP.PLATFORM = 'DESKTOP' THEN 'DESKTOP'
            WHEN BP.PLATFORM = 'CAST' THEN 'CAST'
            WHEN BP.PLATFORM LIKE '%CAST%' THEN 'MULTI W/SMART'
            ELSE 'MULTI OTHERS'
        END AS PLATFORM_V2,
        CASE WHEN SAFE_CAST(BP.USER_ID AS INT64) IS NOT NULL THEN 'LOG' 
        ELSE 'NOT_LOG' 
        END AS FLAG_LOG
    FROM BASE_PLATFORM BP
),
MIGRATION_STEP AS (
    SELECT
        A.USER_ID,
        A.WEEK_ID,
        A.PLATFORM_V2 AS PLATFORM_ORIGIN,
        A.FLAG_LOG,
        A.CUST_TYPE,
        A.SIT_SITE_ID,
        CASE WHEN A.TVM_TOTAL_TIMEFRAME < 3 THEN 'A. MENOR A 3 MIN'
             WHEN A.TVM_TOTAL_TIMEFRAME BETWEEN 3 AND 10 THEN 'B. ENTRE 3 Y 10 MIN'
             WHEN A.TVM_TOTAL_TIMEFRAME BETWEEN 10 AND 30 THEN 'C. ENTRE 10 Y 30 MIN'
             ELSE 'D. MAYOR A 30 MIN'
        END AS TVM_TIMEFRAME,
        B.PLATFORM_V2 AS PLATFORM_DESTINATION_M1
    FROM BASE_PLATFORM_2 A
    LEFT JOIN BASE_PLATFORM_2 B
        ON A.USER_ID = B.USER_ID
        AND A.SIT_SITE_ID = B.SIT_SITE_ID
        AND B.WEEK_ID = DATE_ADD(A.WEEK_ID, INTERVAL 7 DAY)
),
MIGRATION_CLASSIFIED AS (
SELECT
    WEEK_ID,
    PLATFORM_ORIGIN,
    FLAG_LOG,
    CUST_TYPE,
    TVM_TIMEFRAME,
    SIT_SITE_ID,
    USER_ID,
    CASE
        WHEN PLATFORM_DESTINATION_M1 IS NULL THEN 'CHURNED'
        WHEN PLATFORM_ORIGIN = PLATFORM_DESTINATION_M1 THEN 'RETAINED SAME PLATFORM'
        ELSE PLATFORM_DESTINATION_M1
    END AS MIGRATION_FLOW_DESTINATION
FROM MIGRATION_STEP
)
SELECT
    WEEK_ID,
    SIT_SITE_ID,
    PLATFORM_ORIGIN,
    FLAG_LOG,
    CUST_TYPE,
    TVM_TIMEFRAME,
    MIGRATION_FLOW_DESTINATION,
    COUNT(DISTINCT USER_ID) AS TOTAL_USERS
FROM MIGRATION_CLASSIFIED
GROUP BY ALL
