SELECT 
SIT_SITE_ID,
DATE_TRUNC(DS, MONTH) AS MONTH_ID,
DATE_TRUNC(DS, WEEK(MONDAY)) AS WEEK_ID,
DS,
PLATFORM,
CONCAT(SIT_SITE_ID, '-', PLATFORM) AS SITE_PLATFORM, 
SUM (NET_APP_INSTALLS) AS DOWNLOADS,
FROM meli-bi-data.WHOWNER.BT_MKT_MPLAY_INSTALLS
WHERE SIT_SITE_ID IN ('MLA','MLB','MLM','MLC','MCO','MPE','MLU','MEC')
GROUP BY ALL
ORDER BY MONTH_ID DESC, SIT_SITE_ID ASC, PLATFORM ASC