-- description: Métricas de visitantes de MPlay en TV por sitio, plataforma, ciclo de vida y tiempo de visualización, agregadas por día, semana y mes
-- domain: behaviour
-- product: mplay
-- use_case: reporting
-- grain: site, device_platform, life_cycle, viewing_time, day
-- time_grain: daily / weekly / monthly
-- date_column: s.DS
-- date_filter: between (date_from, date_to)
-- threshold_rule:
--   - vista válida: TSV >= 20s
-- metrics:
--   - VIEWERS: cantidad de usuarios distintos con reproducción válida (>=20s)
--   - TVM: minutos totales reproducidos
-- tables_read:
--   - WHOWNER.BT_MKT_MPLAY_SESSION
--   - WHOWNER.BT_MKT_MPLAY_PLAYS
--   - WHOWNER.DM_MKT_MPLAY_RAW_PLAYS
-- joins:
--   - SESSION.SIT_SITE_ID = PLAYS.SIT_SITE_ID
--   - SESSION.USER_ID = PLAYS.USER_ID
--   - SESSION.MELIDATA_SESSION_ID = PLAYS.SESSION_ID
--   - SESSION.SIT_SITE_ID = RAW_PLAYS.SIT_SITE_ID
--   - SESSION.USER_ID = RAW_PLAYS.USER_ID
--   - MONTH(SESSION.DS) = MONTH(RAW_PLAYS.TIM_DAY)
-- owner: data_team

-- VISITORS
DECLARE SITES ARRAY<STRING>;
DECLARE date_from DATE;
DECLARE date_to DATE;

SET SITES = ['MLC', 'MLA', 'MLB', 'MLM', 'MCO', 'MPE', 'MLU', 'MEC'];
SET date_from = '2025-03-01';
SET date_to = CURRENT_DATE();

WITH SESSIONS AS (
  SELECT
    s.SIT_SITE_ID,
    DATE_TRUNC(s.ds, MONTH) AS MONTH_ID,
    s.USER_ID,
    s.SESSION_ID AS MELIDATA_SESSION_ID,
    s.DEVICE_PLATFORM,
    s.ds,
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS s
  WHERE s.ds >= date_from 
    AND s.ds < date_to
    AND s.SIT_SITE_ID IN UNNEST(SITES)
    AND LOWER(DEVICE_PLATFORM) LIKE '/tv%'
  GROUP BY ALL
),

SESSION_PLAY AS (
  SELECT DISTINCT
    s.SIT_SITE_ID,
    s.MONTH_ID,
    DATE_TRUNC(s.DS, WEEK(MONDAY)) AS WEEK_ID,
    s.DS,
    s.USER_ID,
    CASE
      WHEN SUM(R.TVM) < 3 THEN 'A. MENOR A 3 MIN'
      WHEN SUM(R.TVM) BETWEEN 3 AND 10 THEN 'B. ENTRE 3 Y 10 MIN'
      WHEN SUM(R.TVM) BETWEEN 10 AND 30 THEN 'C. ENTRE 10 Y 30 MIN'              
      ELSE 'D. MAYOR A 30 MIN' 
    END AS VIEWING_TIME,
    R.LIFE_CYCLE,
    s.MELIDATA_SESSION_ID,
    CASE
      WHEN UPPER(s.DEVICE_PLATFORM) LIKE '%TIZEN%' THEN 'SAMSUNG'
      WHEN UPPER(s.DEVICE_PLATFORM) LIKE '%ANDR%' THEN 'ANDROID'
      WHEN UPPER(s.DEVICE_PLATFORM) LIKE '%WEB%' THEN 'LG'
      ELSE 'UNKNOWN'
    END AS DEVICE_PLATFORM,
    SUM(P.PLAYBACK_TIME_MILLISECONDS/1000) AS TSV,
    SUM(P.PLAYBACK_TIME_MILLISECONDS/60000) AS TVM 
  FROM SESSIONS AS S 
  LEFT JOIN `meli-bi-data.WHOWNER.DM_MKT_MPLAY_RAW_PLAYS` AS R
    ON S.SIT_SITE_ID = R.SIT_SITE_ID
    AND S.USER_ID = R.USER_ID
    AND DATE_TRUNC(S.DS, MONTH) = DATE_TRUNC(R.TIM_DAY, MONTH)
  LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P 
    ON S.SIT_SITE_ID = P.SIT_SITE_ID
    AND s.USER_ID = P.USER_ID
    AND S.MELIDATA_SESSION_ID = P.SESSION_ID
    AND P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
  WHERE R.TIME_FRAME = 'MONTHLY'                                               
  GROUP BY ALL
),

BASE_MONTHLY AS (
  SELECT 
    'MONTHLY' AS TIMEFRAME_TYPE,
    s.sit_site_id,
    s.MONTH_ID AS TIMEFRAME_ID,
    s.DEVICE_PLATFORM AS DEVICE_PLATFORM,
    CONCAT(S.SIT_SITE_ID, '-', s.DEVICE_PLATFORM) AS SIT_PLATFORM,
    S.VIEWING_TIME,
    S.LIFE_CYCLE,
    COUNT(DISTINCT CASE WHEN S.TSV >= 20 THEN S.USER_ID ELSE NULL END) AS VIEWERS,
    SUM(S.TVM) AS TVM
  FROM SESSION_PLAY s
  GROUP BY ALL
),

BASE_WEEKLY AS (
  SELECT 
    'WEEKLY' AS TIMEFRAME_TYPE,
    s.sit_site_id,
    s.WEEK_ID AS TIMEFRAME_ID,
    s.DEVICE_PLATFORM AS DEVICE_PLATFORM,
    CONCAT(S.SIT_SITE_ID, '-', s.DEVICE_PLATFORM) AS SIT_PLATFORM,
    S.VIEWING_TIME,
    S.LIFE_CYCLE,
    COUNT(DISTINCT CASE WHEN S.TSV >= 20 THEN S.USER_ID ELSE NULL END) AS VIEWERS,
    SUM(S.TVM) AS TVM
  FROM SESSION_PLAY s
  GROUP BY ALL
),

BASE_DAILY AS (
  SELECT 
    'DAILY' AS TIMEFRAME_TYPE,
    s.sit_site_id,
    s.DS AS TIMEFRAME_ID,
    s.DEVICE_PLATFORM AS DEVICE_PLATFORM,
    CONCAT(S.SIT_SITE_ID, '-', s.DEVICE_PLATFORM) AS SIT_PLATFORM,
    S.VIEWING_TIME,
    S.LIFE_CYCLE,
    COUNT(DISTINCT CASE WHEN S.TSV >= 20 THEN S.USER_ID ELSE NULL END) AS VIEWERS,
    SUM(S.TVM) AS TVM
  FROM SESSION_PLAY s
  GROUP BY ALL
)

SELECT * FROM BASE_MONTHLY
UNION ALL
SELECT * FROM BASE_WEEKLY
UNION ALL
SELECT * FROM BASE_DAILY
ORDER BY TIMEFRAME_TYPE ASC, TIMEFRAME_ID DESC, SIT_PLATFORM ASC, VIEWING_TIME ASC, LIFE_CYCLE ASC;