WITH NEW_RET_RECO AS (
  SELECT 
    SIT_SITE_ID,
    USER_ID,
    START_PLAY_TIMESTAMP,
    DS,
    DEVICE_PLATFORM,
    PLAYBACK_TIME_MILLISECONDS,
    DATE_TRUNC(DS, MONTH) AS TIME_FRAME_ID,
    LAG(DS) OVER(PARTITION BY SIT_SITE_ID, USER_ID ORDER BY START_PLAY_TIMESTAMP) AS DS_ANT
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20 
    AND DS <= CURRENT_DATE - 1
),
USERS_WITH_FLAG AS (
  SELECT
    *,
    CASE 
      WHEN DS_ANT IS NULL THEN 'NEW'
      WHEN DATE_DIFF(DS, DS_ANT, DAY) <= 30 THEN 'RETAINED'
      WHEN DATE_DIFF(DS, DS_ANT, DAY) > 30 THEN 'RECOVERED'
      ELSE NULL 
    END AS FLAG_N_R
  FROM NEW_RET_RECO
),
FIRST_PLAY_PER_USER_TF AS (
  SELECT 
    SIT_SITE_ID,
    USER_ID,
    TIME_FRAME_ID,
    FLAG_N_R,
    ROW_NUMBER() OVER(PARTITION BY SIT_SITE_ID, USER_ID, TIME_FRAME_ID ORDER BY START_PLAY_TIMESTAMP) AS RN
  FROM USERS_WITH_FLAG
),
ATTR_TIME_FRAME_ELEGIDO AS (
  SELECT 
    SIT_SITE_ID,
    USER_ID,
    TIME_FRAME_ID,
    FLAG_N_R AS FLAG_N_R_FINAL
  FROM FIRST_PLAY_PER_USER_TF
  WHERE RN = 1
),
CRUCE_FLAG AS (
  SELECT
    A.SIT_SITE_ID,
    A.USER_ID,
    A.TIME_FRAME_ID,
    A.PLAYBACK_TIME_MILLISECONDS,
    A.DEVICE_PLATFORM,
    E.FLAG_N_R_FINAL
  FROM USERS_WITH_FLAG A
  LEFT JOIN ATTR_TIME_FRAME_ELEGIDO E
    ON A.SIT_SITE_ID = E.SIT_SITE_ID 
   AND A.USER_ID = E.USER_ID
   AND A.TIME_FRAME_ID = E.TIME_FRAME_ID
  WHERE E.FLAG_N_R_FINAL = 'RECOVERED'
),
RESUMEN_USER_TF AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    TIME_FRAME_ID,
    FLAG_N_R_FINAL,
    SUM(PLAYBACK_TIME_MILLISECONDS) / 60000 AS TVM_TOTAL_TIMEFRAME,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS ELSE 0 END) / 60000 AS TOTAL_TV,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS ELSE 0 END) / 60000 AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS ELSE 0 END) / 60000 AS TOTAL_DESKTOP
  FROM CRUCE_FLAG
  GROUP BY SIT_SITE_ID, USER_ID, TIME_FRAME_ID, FLAG_N_R_FINAL
)
SELECT
  SIT_SITE_ID,
  TIME_FRAME_ID AS MONTH_ID,
  CASE 
    WHEN TVM_TOTAL_TIMEFRAME < 3 THEN 'A. MENOR A 3 MIN'
    WHEN TVM_TOTAL_TIMEFRAME BETWEEN 3 AND 10 THEN 'B. ENTRE 3 Y 10 MIN'
    WHEN TVM_TOTAL_TIMEFRAME BETWEEN 10 AND 30 THEN 'C. ENTRE 10 Y 30 MIN'
    ELSE 'D. MAYOR A 30 MIN'
  END AS TVM_TIMEFRAME,
  FLAG_N_R_FINAL AS CUST_TYPE,
  CASE 
    WHEN SAFE_CAST(USER_ID AS INT64) IS NULL THEN 'NOT_LOG'
    ELSE 'LOG'
  END AS FLAG_LOG,
  CONCAT(
    CASE WHEN TOTAL_TV > 0 THEN 'SMART' ELSE '' END,
    CASE WHEN TOTAL_MOBILE > 0 THEN 'MOBILE' ELSE '' END,
    CASE WHEN TOTAL_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END
  ) AS PLATFORM,
  SUM(TVM_TOTAL_TIMEFRAME) AS TVM_TOTAL,
  COUNT(DISTINCT USER_ID) AS TOTAL_USERS
FROM RESUMEN_USER_TF
WHERE TIME_FRAME_ID >= DATE '2024-01-01'
GROUP BY 
  SIT_SITE_ID,
  TIME_FRAME_ID,
  TVM_TIMEFRAME,
  FLAG_N_R_FINAL,
  FLAG_LOG,
  PLATFORM
ORDER BY MONTH_ID;
