-- description: Clasificación de usuarios MPlay según score de engagement calculado por actividad histórica, segmentación de lifecycle y características del usuario
-- domain: behaviour
-- product: mplay
-- use_case: user_segmentation
-- grain: user
-- time_grain: aggregated_period
-- date_column: SN.SNAPSHOT_DATE
-- date_filter: <= current_date
-- metrics:
-- - SCORE_ENG: score de engagement ponderado por meses de actividad high, medium y low
-- - TOTAL_USERS: cantidad de usuarios únicos
-- - CALIDAD_ABSOLUTA: clasificación de engagement (A/B/C)
-- tables_read:
-- - MPLAY.MPLAY_USER_LIFECYCLE_SNAPSHOT
-- - MPLAY.LAST_MPLAY_USER_LIFECYCLE_SNAPSHOT
-- joins:
-- - SNAPSHOT.SIT_SITE_ID = USER.SIT_SITE_ID
-- - SNAPSHOT.USER_ID = USER.USER_ID
-- owner: data_team

WITH USER_MONTHS AS (
  SELECT
    SN.SIT_SITE_ID,
    SN.USER_ID,
    UM.TYPE_USER,
    UM.SEGMENT_LIFE_CYCLE,
    UM.BUYER_CATEGORY,
    CASE WHEN DATE_DIFF(CURRENT_DATE, UM.LAST_PLAY_DATE, MONTH) <= 6 THEN DATE_DIFF(CURRENT_DATE, UM.LAST_PLAY_DATE, MONTH) ELSE 7 END AS AGING_MONTHS,
    DATE_DIFF(CURRENT_DATE(), UM.FIRST_PLAY_DATE, MONTH) AS edad_en_play,
    DATE_DIFF(CURRENT_DATE(), CASE WHEN UM.FIRST_PLAY_DATE <= DATE '2024-08-01' THEN DATE '2024-08-01' ELSE UM.FIRST_PLAY_DATE END, MONTH) AS total_meses_posible_Actividad,
    COUNT(DISTINCT CASE WHEN (SN.SEGMENT_LIFE_CYCLE LIKE '%RETENT%' OR SN.SEGMENT_LIFE_CYCLE LIKE '%EARLY%') AND SN.TYPE_USER LIKE 'HIGH%' THEN SN.SNAPSHOT_DATE ELSE NULL END) AS TOTAL_HIGH,
    COUNT(DISTINCT CASE WHEN (SN.SEGMENT_LIFE_CYCLE LIKE '%RETENT%' OR SN.SEGMENT_LIFE_CYCLE LIKE '%EARLY%') AND SN.TYPE_USER LIKE 'MED%' THEN SN.SNAPSHOT_DATE ELSE NULL END) AS TOTAL_MED,
    COUNT(DISTINCT CASE WHEN (SN.SEGMENT_LIFE_CYCLE LIzKE '%RETENT%' OR SN.SEGMENT_LIFE_CYCLE LIKE '%EARLY%') AND SN.TYPE_USER LIKE 'LOW%' THEN SN.SNAPSHOT_DATE ELSE NULL END) AS TOTAL_LOW
  FROM `meli-sbox.MPLAY.MPLAY_USER_LIFECYCLE_SNAPSHOT` AS SN
  INNER JOIN `meli-sbox.MPLAY.LAST_MPLAY_USER_LIFECYCLE_SNAPSHOT` AS UM 
    ON UM.SIT_SITE_ID = SN.SIT_SITE_ID
    AND UM.USER_ID = SN.USER_ID
    AND SN.SNAPSHOT_DATE >= UM.FIRST_PLAY_DATE
    AND UM.FIRST_PLAY_DATE <= CURRENT_DATE()
  WHERE SN.SNAPSHOT_DATE <= CURRENT_DATE()
  GROUP BY ALL
)
SELECT
  SIT_SITE_ID,
  TYPE_USER,
  SEGMENT_LIFE_CYCLE,
  BUYER_CATEGORY,
  AGING_MONTHS,
  EDAD_EN_PLAY,
  CASE
    WHEN SCORE_ENG >= 0.35 THEN 'A_HIGH_ENG'
    WHEN SCORE_ENG >= 0.20 AND SCORE_ENG < 0.35 THEN 'B_MEDIUM_ENG'
    ELSE 'C_LOW_ENG'
  END AS CALIDAD_ABSOLUTA,
  COUNT(DISTINCT USER_ID) AS TOTAL_USERS,
FROM(
    ( SELECT
        *,
        SAFE_DIVIDE((TOTAL_HIGH * 3 + TOTAL_MED * 2 + TOTAL_LOW * 1), (TOTAL_MESES_POSIBLE_ACTIVIDAD * 3)) AS SCORE_ENG
      FROM USER_MONTHS
    )
  )
GROUP BY ALL 