WITH SESSIONS AS (
  SELECT
    t.*
  FROM (
      SELECT
          s.SIT_SITE_ID,
          DATE_TRUNC(s.ds, MONTH) AS MONTH_ID,
          DATE_TRUNC(s.ds, WEEK(MONDAY)) AS WEEK_ID,
          s.ds,
          ORIGIN_PATH AS FIRST_EVENT_SOURCE,
          FIRST_TRACK AS FIRST_EVENT_PATH,
          s.USER_ID,
          s.SESSION_ID AS MELIDATA_SESSION_ID,
          s.DEVICE_PLATFORM,
          IF(((S.HAS_SEARCH IS TRUE OR S.HAS_VCP IS TRUE OR S.HAS_VCM IS TRUE OR HAS_PLAY IS TRUE) OR TOTAL_FEED_IMPRESSIONS > 1), TRUE, FALSE) AS FLAG_VALID_VISIT,
          HAS_PLAY,
          S.TOTAL_SESSION_MILLISECOND / 1000 AS session_time_sec,
          ROW_NUMBER() OVER (PARTITION BY s.USER_ID ORDER BY s.ds ASC, FIRST_PLAY_DATETIME ASC) AS rn 
      FROM
          `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS s
      WHERE
          s.ds >= '2024-12-30'
          AND s.ds < CURRENT_DATE()
          AND s.SIT_SITE_ID IN UNNEST(['MLC', 'MLA', 'MLB', 'MLM', 'MCO', 'MPE', 'MLU', 'MEC'])
          AND S.USER_ID IN ('1014210361', '1018725835'/* ENLISTAR USUARIOS ACÁ */)
  ) AS t
  WHERE
      t.rn = 1
      -- AND FLAG_VALID_VISIT IS TRUE
      -- AND HAS_PLAY IS TRUE
),
TOTAL_SESSIONS AS (
  SELECT
    s.SIT_SITE_ID,
    s.USER_ID,
    COUNT(DISTINCT s.SESSION_ID) AS UNIQUE_SESSIONS
  FROM
      `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS s
  WHERE
      s.ds >= '2024-12-30'
      AND s.ds < CURRENT_DATE()
      AND s.SIT_SITE_ID IN UNNEST(['MLC', 'MLA', 'MLB', 'MLM', 'MCO', 'MPE', 'MLU', 'MEC'])
      AND S.USER_ID IN ('1014210361', '1018725835'/* ENLISTAR USUARIOS ACÁ */)
  GROUP BY
      s.SIT_SITE_ID,
      s.USER_ID
),
ORIGIN_BASE AS (
  SELECT
    S.SIT_SITE_ID,
    S.USER_ID,
    S.MONTH_ID,
    S.WEEK_ID,
    S.DS,
    S.FIRST_EVENT_SOURCE,
    S.MELIDATA_SESSION_ID,
    S.DEVICE_PLATFORM,
    CASE
      WHEN S.DEVICE_PLATFORM IN ('/tv/android') THEN '/tv/android'
      WHEN S.DEVICE_PLATFORM IN ('/tv/Tizen') THEN '/tv/Tizen'
      WHEN S.DEVICE_PLATFORM IN ('/tv/Web0S') THEN '/tv/Web0S'
      ELSE COALESCE(o.origin, 'Otros')
    END AS Origin,
    TS.UNIQUE_SESSIONS
  FROM SESSIONS AS S
  LEFT JOIN TOTAL_SESSIONS AS TS
    ON S.SIT_SITE_ID = TS.SIT_SITE_ID
      AND S.USER_ID = TS.USER_ID
  LEFT JOIN meli-sbox.MPLAY.CLASIFICATION_ORIGINS AS o
    ON COALESCE(FIRST_EVENT_SOURCE, 'NULL') = COALESCE(o.origin, 'NULL')
),
PLAYS_PIVOT AS (
    SELECT
        P.USER_ID,
        SUM(CASE WHEN C.CONTENT_TYPE = 'EPISODE' THEN 1 ELSE 0 END) AS PLAYS_EPISODE,
        SUM(CASE WHEN C.CONTENT_TYPE = 'MOVIE' THEN 1 ELSE 0 END) AS PLAYS_MOVIE,
        SUM(CASE WHEN C.CONTENT_TYPE = 'SEASON' THEN 1 ELSE 0 END) AS PLAYS_SEASON,
        SUM(CASE WHEN C.CONTENT_TYPE = 'SHOW' THEN 1 ELSE 0 END) AS PLAYS_SHOW,
        SUM(CASE WHEN C.CONTENT_TYPE = 'LIVEEVENT' THEN 1 ELSE 0 END) AS PLAYS_LIVEEVENT,
        SUM(CASE WHEN C.CONTENT_TYPE = 'LIVECHANNEL' THEN 1 ELSE 0 END) AS PLAYS_LIVECHANNEL
    FROM
        `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
    INNER JOIN
        `meli-bi-data.WHOWNER.LK_MKT_MPLAY_CATALOGUE` AS C
        ON P.CONTENT_ID = C.CONTENT_ID
    WHERE
        P.PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
        AND P.USER_ID IN ('1014210361', '1018725835'/* ENLISTAR USUARIOS ACÁ */) 
        AND C.CONTENT_TYPE IN ('EPISODE', 'MOVIE', 'SEASON', 'SHOW', 'LIVEEVENT', 'LIVECHANNEL')
    GROUP BY
        P.USER_ID
)
SELECT 
  a.*,
  CONCAT(Clasificacion, '-', Subclasificacion) AS touchpoint,
  Clasificacion,
  Subclasificacion,
  COALESCE(p.PLAYS_EPISODE, 0) AS PLAYS_EPISODE,
  COALESCE(p.PLAYS_MOVIE, 0) AS PLAYS_MOVIE,
  COALESCE(p.PLAYS_SEASON, 0) AS PLAYS_SEASON,
  COALESCE(p.PLAYS_SHOW, 0) AS PLAYS_SHOW,
  COALESCE(p.PLAYS_LIVEEVENT, 0) AS PLAYS_LIVEEVENT,
  COALESCE(p.PLAYS_LIVECHANNEL, 0) AS PLAYS_LIVECHANNEL
FROM ORIGIN_BASE AS a
LEFT JOIN meli-sbox.MPLAY.CLASIFICATION_ORIGINS AS b
  ON a.Origin = b.origin
LEFT JOIN PLAYS_PIVOT AS p
  ON a.USER_ID = p.USER_ID;