WITH USER_MONTHS AS (
  SELECT
    SN.SIT_SITE_ID,
    SN.USER_ID,
    UM.TYPE_USER,
    UM.SEGMENT_LIFE_CYCLE,
    -- UM.BUYER_CATEGORY,
    CASE WHEN DATE_DIFF(CURRENT_DATE, UM.LAST_PLAY_DATE, MONTH) <= 3 THEN DATE_DIFF(CURRENT_DATE, UM.LAST_PLAY_DATE, MONTH) ELSE NULL END AS AGING_MONTHS,
    DATE_DIFF(CURRENT_DATE(), UM.FIRST_PLAY_DATE, MONTH) AS edad_en_play,
    DATE_DIFF(CURRENT_DATE(), CASE WHEN UM.FIRST_PLAY_DATE <= DATE '2024-08-01' THEN DATE '2024-08-01' ELSE UM.FIRST_PLAY_DATE END, MONTH) AS total_meses_posible_Actividad,
    COUNT(DISTINCT CASE WHEN (SN.SEGMENT_LIFE_CYCLE LIKE '%RETENT%' OR SN.SEGMENT_LIFE_CYCLE LIKE '%EARLY%') AND SN.TYPE_USER LIKE 'HIGH%' THEN SN.SNAPSHOT_DATE ELSE NULL END) AS TOTAL_HIGH,
    COUNT(DISTINCT CASE WHEN (SN.SEGMENT_LIFE_CYCLE LIKE '%RETENT%' OR SN.SEGMENT_LIFE_CYCLE LIKE '%EARLY%') AND SN.TYPE_USER LIKE 'MED%' THEN SN.SNAPSHOT_DATE ELSE NULL END) AS TOTAL_MED,
    COUNT(DISTINCT CASE WHEN (SN.SEGMENT_LIFE_CYCLE LIKE '%RETENT%' OR SN.SEGMENT_LIFE_CYCLE LIKE '%EARLY%') AND SN.TYPE_USER LIKE 'LOW%' THEN SN.SNAPSHOT_DATE ELSE NULL END) AS TOTAL_LOW
  FROM `meli-sbox.MPLAY.MPLAY_USER_LIFECYCLE_SNAPSHOT` AS SN
  INNER JOIN `meli-sbox.MPLAY.LAST_MPLAY_USER_LIFECYCLE_SNAPSHOT` AS UM 
    ON UM.SIT_SITE_ID = SN.SIT_SITE_ID
    AND UM.USER_ID = SN.USER_ID
    AND SN.SNAPSHOT_DATE >= UM.FIRST_PLAY_DATE
    AND UM.FIRST_PLAY_DATE <= CURRENT_DATE()
  WHERE SN.SNAPSHOT_DATE <= CURRENT_DATE()
  AND SN.SIT_SITE_ID IN ('MLB', 'MLM')
  AND DATE_DIFF(CURRENT_DATE, UM.LAST_PLAY_DATE, MONTH) <= 3
  GROUP BY ALL
),
CALCULATED_SCORES AS (
    SELECT
        *,
        SAFE_DIVIDE((TOTAL_HIGH * 3 + TOTAL_MED * 2 + TOTAL_LOW * 1), (TOTAL_MESES_POSIBLE_ACTIVIDAD * 3)) AS SCORE_ENG
    FROM USER_MONTHS
),
SCORED_USERS AS (
    SELECT
        *,
        CASE
            WHEN SCORE_ENG >= 0.35 THEN 'A_HIGH_ENG'
            WHEN SCORE_ENG >= 0.20 AND SCORE_ENG < 0.35 THEN 'B_MEDIUM_ENG'
            ELSE 'C_LOW_ENG'
        END AS CALIDAD_ABSOLUTA,
        ROW_NUMBER() OVER(
            PARTITION BY SIT_SITE_ID, USER_ID
            ORDER BY 
                AGING_MONTHS ASC,        
                SEGMENT_LIFE_CYCLE ASC   
        ) as rn
    FROM CALCULATED_SCORES
)
SELECT
  SIT_SITE_ID,
  USER_ID,
 -- SEGMENT_LIFE_CYCLE,
  -- AGING_MONTHS,
  -- CALIDAD_ABSOLUTA
FROM SCORED_USERS
WHERE
    rn = 1
    AND SEGMENT_LIFE_CYCLE IN ('6.CHURN', '7.LATENT', '8.STOCK')
    AND CALIDAD_ABSOLUTA IN ('A_HIGH_ENG')