SELECT 
SIT_SITE_ID,
WEEK_ID,
--MONTH_ID,
CASE WHEN LOWER(DEVICE_PLATFORM) LIKE '%/tv%' then 'SMART'
     WHEN LOWER(DEVICE_PLATFORM) LIKE '%mobile%'then 'MOBILE'
     WHEN LOWER(DEVICE_PLATFORM) LIKE '%desktop%'then 'DESKTOP'
     ELSE null 
     END AS PLATFORM,      
CASE WHEN SAFE_CAST(user_id as int64) IS NOT null THEN 'LOG' 
     ELSE 'NOT_LOG' 
     END AS FLAG_LOG,
COUNT(DISTINCT USER_ID) AS NEW_VIEWERS,
SUM(TVM) AS TVM
FROM (
SELECT
SIT_SITE_ID,
USER_ID,
DATE_TRUNC(DS, WEEK(MONDAY)) as WEEK_ID,
--DATE_TRUNC(DS,MONTH) AS MONTH_ID,
DEVICE_PLATFORM,
PLAYBACK_TIME_MILLISECONDS/60000 AS TVM
FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
WHERE PLAYBACK_TIME_MILLISECONDS/1000>=20
QUALIFY ROW_NUMBER()OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY START_PLAY_TIMESTAMP asc) = 1
) AS a
WHERE LOWER(DEVICE_PLATFORM) LIKE '%/tv%'
GROUP BY ALL
ORDER BY WEEK_ID;