SELECT DISTINCT
P.SIT_SITE_ID,
DATE_TRUNC(DS, WEEK(MONDAY)) as WEEK_ID,
LOWER(DEVICE_PLATFORM) PLATFORM,
--CASE WHEN P.DS = FIRST_DATE THEN 'NEW' ELSE 'OLD' END AS FLAG_NEW,
--CASE WHEN SAFE_CAST(P.USER_ID AS INT64) IS NOT NULL THEN 'LOG' ELSE 'NOT_LOG' END AS FLAG_LOG_SESSION,
--COUNT(DISTINCT P.SESSION_ID) AS SESSION_VIEWERS,
COUNT(DISTINCT P.USER_ID) AS VIEWERS_SMART,
SUM(PLAYBACK_TIME_MILLISECONDS/60000) AS TVM_SMART
FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` P
LEFT JOIN  (
      select
      USER_ID,
      SIT_SITE_ID,
      MIN(DS) AS FIRST_DATE
      FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
      WHERE P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
      GROUP BY ALL
) AS FP ON FP.USER_ID = P.USER_ID AND FP.SIT_SITE_ID = P.SIT_SITE_ID
WHERE LOWER(DEVICE_PLATFORM) LIKE '/tv%'
AND PLAYBACK_TIME_MILLISECONDS/1000 >=20
GROUP BY ALL
ORDER BY WEEK_ID;