SELECT DISTINCT
--DS,
--LOWER(DEVICE_PLATFORM) AS PLATFORM,
--P.SIT_SITE_ID,
--CASE WHEN P.DS = FIRST_DATE THEN 'NEW' ELSE 'OLD' END AS FLAG_NEW,
--CASE WHEN SAFE_CAST(P.USER_ID AS INT64) IS NOT NULL THEN 'LOG' ELSE 'NOT_LOG' END AS FLAG_LOG_SESSION,
--COUNT(DISTINCT P.SESSION_ID) AS SESSION_VIEWERS,
COUNT(DISTINCT P.USER_ID) AS VIEWERS,
SUM(PLAYBACK_TIME_MILLISECONDS/60000) AS TVM
FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
LEFT JOIN  (
      SELECT
      USER_ID,
      SIT_SITE_ID,
      MIN(DS) AS FIRST_DATE
      FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
      WHERE p.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
      GROUP BY ALL
) AS FP ON FP.USER_ID =  P.USER_ID AND FP.SIT_SITE_ID = P.SIT_SITE_ID
WHERE LOWER(DEVICE_PLATFORM) LIKE '/tv%'
AND PLAYBACK_TIME_MILLISECONDS/1000 >=20
--AND DS <= '2025-03-31'
GROUP BY ALL;