WITH BASE AS (
    SELECT
SIT_SITE_ID,
USER_ID,
DATE_TRUNC(TIM_DAY, MONTH) as MONTH_ID,
CASE WHEN ROUND(SUM(TVM), 2) < 3 THEN 'A. MENOR A 3 MIN'
     WHEN ROUND(SUM(TVM), 2)  BETWEEN 3 AND 10 THEN 'B. ENTRE 3 Y 10 MIN'
     WHEN ROUND(SUM(TVM), 2)  BETWEEN 10 AND 30 THEN 'C. ENTRE 10 Y 30 MIN'              
     ELSE 'D. MAYOR A 30 MIN' 
    END AS TVM_TIMEFRAME,
LIFE_CYCLE,
FLAG_LOG,
PLATFORM_AGG,
SUM(TVM) AS TVM_TOTAL
FROM `meli-bi-data.WHOWNER.DM_MKT_MPLAY_RAW_PLAYS`
WHERE TIME_FRAME = 'MONTHLY'
GROUP BY ALL
)
SELECT
SIT_SITE_ID,
MONTH_ID,
TVM_TIMEFRAME,
LIFE_CYCLE AS CUST_TYPE,
FLAG_LOG,
PLATFORM_AGG AS PLATFORM,
ROUND(SUM(TVM_TOTAL), 2) TVM_TOTAL,
COUNT(DISTINCT USER_ID) AS TOTAL_USERS
FROM BASE
GROUP BY ALL
-- MONTHLY