WITH BUYERS_MARKETPLACE AS (
  SELECT DISTINCT 
    DATE_TRUNC(bd.ord_created_dt, MONTH) AS MONTH_ID,
    bd.sit_site_id AS SIT_SITE_ID,
    CAST(bd.ord_buyer.id AS STRING) AS USER_ID
  FROM `meli-bi-data.WHOWNER.BT_ORD_ORDERS` AS bd
  WHERE bd.ord_tgmv_flg = TRUE
    AND COALESCE(bd.ord_auto_offer_flg, FALSE) = FALSE
    AND bd.sit_site_id IN ('MLA','MLM','MLC','MCO','MLU','MPE','MLB', 'MEC')
    AND bd.ord_closed_dt IS NOT NULL
    AND bd.ord_category.marketplace_id = 'TM'
    AND ord_order_mshops_flg = FALSE
    AND ord_order_proximity_flg = FALSE
    AND bd.ord_created_dt >= '2023-01-01'
),
VIEWERS_PLATFORM AS (
  SELECT
    DATE_TRUNC(DS, MONTH) AS MONTH_ID,
    SIT_SITE_ID,
    CAST(USER_ID AS STRING) AS USER_ID,
    CUS_CUST_ID,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_DESKTOP,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%CAST%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_CAST
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND DS <= CURRENT_DATE() - 1
  GROUP BY 1, 2, 3, 4
),
VIEWERS_PLATFORM_LABELLED AS (
  SELECT
    MONTH_ID,
    SIT_SITE_ID,
    USER_ID,
    CUS_CUST_ID,
    CONCAT(
      CASE WHEN TOTAL_TV > 0 THEN 'SMART' ELSE '' END,
      CASE WHEN TOTAL_MOBILE > 0 THEN 'MOBILE' ELSE '' END,
      CASE WHEN TOTAL_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END,
      CASE WHEN TOTAL_CAST > 0 THEN 'CAST' ELSE '' END
    ) AS PLATFORM_ACTUAL
  FROM VIEWERS_PLATFORM
),
SUBSCRIPTIONS_L6 AS (
  SELECT DISTINCT
    CUS_CUST_ID_BUY
  FROM `meli-bi-data.WHOWNER.BT_MP_PAY_SUBSCRIPTION`
  WHERE SUB_STATUS IN ('active','ready')
    AND CUS_CUST_ID_SEL IN (797214326, 797215821, 797215856, 797215866, 797215778)
),
SUMMARY_MELIMAS AS (
  SELECT
    v.MONTH_ID,
    v.SIT_SITE_ID,
    v.PLATFORM_ACTUAL,
    COUNT(DISTINCT v.USER_ID) AS TOTAL_VIEWERS,
    COUNT(DISTINCT s.CUS_CUST_ID_BUY) AS TOTAL_SUSCRIPTORES
  FROM VIEWERS_PLATFORM_LABELLED v
  LEFT JOIN SUBSCRIPTIONS_L6 s
    ON v.CUS_CUST_ID = s.CUS_CUST_ID_BUY
  GROUP BY 1, 2, 3
)
SELECT *
FROM SUMMARY_MELIMAS
ORDER BY MONTH_ID, SIT_SITE_ID, PLATFORM_ACTUAL;



















DECLARE SITES ARRAY<STRING>;
DECLARE date_from DATE;
DECLARE date_to DATE;
SET SITES = ['MLC', 'MLA', 'MLB', 'MLM', 'MCO', 'MPE', 'MLU', 'MEC'];
SET date_from = '2025-01-27';
SET date_to = current_date();
WITH SESSIONS AS
              ( SELECT
                      S.SIT_SITE_ID,
                      DATE_TRUNC(S.DS, MONTH) as MONTH_ID, --Month
                      DATE_TRUNC(S.DS, WEEK(MONDAY)) as FECHA_WEEK, --Week
                      S.DS, --Fecha
                      ORIGIN_PATH AS FIRST_EVENT_SOURCE,
                      FIRST_TRACK AS FIRST_EVENT_PATH,
                      FIRST_PLAY_DATETIME AS PLAY_TIMESTAMP,
                      S.USER_ID,
                      S.CUS_CUST_ID,
                      S.SESSION_ID AS MELIDATA_SESSION_ID,
                      IF(((S.HAS_SEARCH IS TRUE OR S.HAS_VCP IS TRUE OR S.HAS_VCM IS TRUE OR HAS_PLAY IS TRUE) OR TOTAL_FEED_IMPRESSIONS > 1),TRUE,FALSE) AS FLAG_VALID_VISIT,
                      HAS_PLAY,
                      S.TOTAL_SESSION_MILLISECOND/1000 AS SESSION_TIME_SEC
              FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS S
              WHERE S.DS >= date_from
              AND S.DS < date_to
              AND S.SIT_SITE_ID IN UNNEST(SITES)
              GROUP BY ALL
),
SESSION_PLAY AS   (
              SELECT DISTINCT
                    S.SIT_SITE_ID,
                    S.MONTH_ID,
                    S.FECHA_WEEK,
                    S.DS,
                    S.FIRST_EVENT_SOURCE,
                    S.FIRST_EVENT_PATH,
                    S.PLAY_TIMESTAMP,
                    S.USER_ID,
                    S.CUS_CUST_ID,
                    S.MELIDATA_SESSION_ID,
                    S.FLAG_VALID_VISIT,
                    S.HAS_PLAY,
                    S.SESSION_TIME_SEC,
                    P.CONTENT_ID,
                    P.PLAYBACK_TIME_MILLISECONDS,
                    SUM(P.PLAYBACK_TIME_MILLISECONDS/1000) AS TSV,
                    SUM(P.PLAYBACK_TIME_MILLISECONDS/60000) AS TVM
              FROM SESSIONS AS S
              LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P ON S.SIT_SITE_ID = P.SIT_SITE_ID
                                                                        AND S.USER_ID = P.USER_ID
                                                                        AND S.MELIDATA_SESSION_ID = P.SESSION_ID
                                                                        AND P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
              GROUP BY ALL
),
CATALOG1 AS (
  SELECT
        C.SIT_SITE_ID,
        C.CONTENT_TYPE,
        C.CONTENT_ID,
        CASE WHEN C.CONTENT_TYPE IN ('EPISODE','SHOW') THEN 'SERIES'
             ELSE C.CONTENT_TYPE
             END AS CONTENT_TYPE_ADJUSTED,
        C.SEASON_NUMBER,
        C.EPISODE_NUMBER,
        C.ORIGINAL_TITLE AS ORIGINAL_TITLE_2,
        C.TITLE_ADJUSTED,
        C.CONTENT_PROVIDER,
        C.GENRE,
        --C.RUNTIME,
        CAST(RTRIM(C.RUNTIME, 's') AS int) AS RUNTIME2
FROM `WHOWNER.LK_MKT_MPLAY_CATALOGUE` C
LEFT JOIN (
          SELECT
                CONTENT_ID,
                SHOW_ID,
                SIT_SITE_ID,
                ORIGINAL_TITLE
          FROM `WHOWNER.LK_MKT_MPLAY_CATALOGUE`
          WHERE CONTENT_TYPE = 'SHOW'
          ) S ON C.SHOW_ID = S.CONTENT_ID AND C.SIT_SITE_ID = S.SIT_SITE_ID
),
EPISODIO_1 AS (
SELECT DISTINCT
S.SIT_SITE_ID,
--S.DS,
C1.TITLE_ADJUSTED,
C1.CONTENT_ID,
SUM(S.TSV) AS TSV,
C1.RUNTIME2,
SUM(S.TSV) / C1.RUNTIME2 AS COMPLETION_RATE_E1,
CASE WHEN (SUM(S.TSV) / C1.RUNTIME2) >= 0.9 THEN 1
      ELSE 0
      END AS COMPLETITUD_E1,
S.USER_ID,
S.CUS_CUST_ID
FROM SESSION_PLAY S
LEFT JOIN CATALOG1 C1 ON S.SIT_SITE_ID = C1.SIT_SITE_ID AND S.CONTENT_ID = C1.CONTENT_ID
WHERE C1.CONTENT_ID IN ('2c703f9b6ac941099f3481c96cca6d1c')
GROUP BY ALL
),
EPISODIO_2 AS (
SELECT DISTINCT
S.SIT_SITE_ID,
--S.DS,
C1.TITLE_ADJUSTED,
C1.CONTENT_ID,
SUM(S.TSV) AS TSV,
C1.RUNTIME2,
SUM(S.TSV) / C1.RUNTIME2 AS COMPLETION_RATE_E2,
CASE WHEN (SUM(S.TSV) / C1.RUNTIME2) >= 0.9 THEN 1
      ELSE 0
      END AS COMPLETITUD_E2,
S.USER_ID,
S.CUS_CUST_ID
FROM SESSION_PLAY S
LEFT JOIN CATALOG1 C1 ON S.SIT_SITE_ID = C1.SIT_SITE_ID AND S.CONTENT_ID = C1.CONTENT_ID
WHERE C1.CONTENT_ID IN ('2740a6f6d94341f5b0f61bd08a5557ac')
GROUP BY ALL
),
EPISODIO_3 AS (
SELECT DISTINCT
S.SIT_SITE_ID,
--S.DS,
C1.TITLE_ADJUSTED,
C1.CONTENT_ID,
SUM(S.TSV) AS TSV,
C1.RUNTIME2,
SUM(S.TSV) / C1.RUNTIME2 AS COMPLETION_RATE_E3,
CASE WHEN (SUM(S.TSV) / C1.RUNTIME2) >= 0.9 THEN 1
      ELSE 0
      END AS COMPLETITUD_E3,
S.USER_ID,
S.CUS_CUST_ID
FROM SESSION_PLAY S
LEFT JOIN CATALOG1 C1 ON S.SIT_SITE_ID = C1.SIT_SITE_ID AND S.CONTENT_ID = C1.CONTENT_ID
WHERE C1.CONTENT_ID IN ('75325837fe774b6695ab8ec81ca80922')
GROUP BY ALL
),
SUBSCRIPTIONS_L6 AS
    (SELECT DISTINCT
            S.CUS_CUST_ID_BUY,
            --P.CUS_CUST_ID_SEL
    FROM meli-bi-data.WHOWNER.BT_MP_PAY_SUBSCRIPTION S
    --LEFT JOIN meli-bi-data.WHOWNER.DM_LYL_DIM_PARTNER_PLAN P ON P.SUB_PLAN_CODE = S.SUB_PLAN_ID
WHERE S.SUB_STATUS IN ('active','ready')
AND CUS_CUST_ID_SEL IN (797214326, 797215821, 797215856, 797215866, 797215778)
),

PARTNERS_MAX AS
(SELECT DISTINCT
            S.CUS_CUST_ID_BUY,
            P.CUS_CUST_ID_SEL
    FROM meli-bi-data.WHOWNER.BT_MP_PAY_SUBSCRIPTION S
    LEFT JOIN meli-bi-data.WHOWNER.DM_LYL_DIM_PARTNER_PLAN P ON P.SUB_PLAN_CODE = S.SUB_PLAN_ID
WHERE S.SUB_STATUS IN ('active','ready')
AND P.CUS_CUST_ID_SEL IN (537349112, 537356510, 585871537, 694901138, 694903096)
)

SELECT DISTINCT
      E1.SIT_SITE_ID,
      E1.CUS_CUST_ID,
      COALESCE(COMPLETITUD_E1,0) as COMPLETITUD_E1,
      COALESCE(COMPLETITUD_E2,0) as COMPLETITUD_E2,
      COALESCE(COMPLETITUD_E3,0) as COMPLETITUD_E3,
      COALESCE(COMPLETION_RATE_E1,0) as COMPLETION_RATE_E1,
      COALESCE(COMPLETION_RATE_E2,0) as COMPLETION_RATE_E2,
      COALESCE(COMPLETION_RATE_E3,0) as COMPLETION_RATE_E3,
      CASE WHEN E1.CUS_CUST_ID IN (SELECT CUS_CUST_ID_BUY FROM SUBSCRIPTIONS_L6) THEN 1 ELSE 0 END AS SUSCRIPCION_MELI,
      CASE WHEN E1.CUS_CUST_ID IN (SELECT CUS_CUST_ID_BUY FROM PARTNERS_MAX) THEN 1 ELSE 0 END AS SUSCRIPCION_MAX
FROM EPISODIO_1 E1
LEFT JOIN EPISODIO_2 E2 ON E2.CUS_CUST_ID = E1.CUS_CUST_ID
LEFT JOIN EPISODIO_3 E3 ON E3.CUS_CUST_ID = E1.CUS_CUST_ID
--LEFT JOIN SUBSCRIPTIONS_L6 SUB ON SUB.CUS_CUST_ID_BUY = E1.CUS_CUST_ID
WHERE E1.CUS_CUST_ID IS NOT null
GROUP BY ALL




WITH BUYERS_MARKETPLACE AS (
  SELECT DISTINCT 
    DATE_TRUNC(bd.ord_created_dt, MONTH) AS MONTH_ID,
    bd.sit_site_id AS SIT_SITE_ID,
    CAST(bd.ord_buyer.id AS STRING) AS USER_ID
  FROM `meli-bi-data.WHOWNER.BT_ORD_ORDERS` AS bd
  WHERE bd.ord_tgmv_flg = TRUE
    AND COALESCE(bd.ord_auto_offer_flg, FALSE) = FALSE
    AND bd.sit_site_id IN ('MLA','MLM','MLC','MCO','MLU','MPE','MLB', 'MEC')
    AND bd.ord_closed_dt IS NOT NULL
    AND bd.ord_category.marketplace_id = 'TM'
    AND ord_order_mshops_flg = FALSE
    AND ord_order_proximity_flg = FALSE
    AND bd.ord_created_dt >= '2023-01-01'
),
VIEWERS_PLATFORM AS (
  SELECT
    DATE_TRUNC(DS, MONTH) AS MONTH_ID,
    SIT_SITE_ID,
    CAST(USER_ID AS STRING) AS USER_ID,
    CUS_CUST_ID,
    ROUND(SUM(PLAYBACK_TIME_MILLISECONDS) / 60000 , 2) AS TVM,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_DESKTOP,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%CAST%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_CAST
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND DS <= CURRENT_DATE() - 1
  GROUP BY 1, 2, 3, 4
),
VIEWERS_PLATFORM_LABELLED AS (
  SELECT
    MONTH_ID,
    SIT_SITE_ID,
    USER_ID,
    CUS_CUST_ID,
    TVM,  -- ADDED!
    CONCAT(
      CASE WHEN TOTAL_TV > 0 THEN 'SMART' ELSE '' END,
      CASE WHEN TOTAL_MOBILE > 0 THEN 'MOBILE' ELSE '' END,
      CASE WHEN TOTAL_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END,
      CASE WHEN TOTAL_CAST > 0 THEN 'CAST' ELSE '' END
    ) AS PLATFORM_ACTUAL
  FROM VIEWERS_PLATFORM
),
SUBSCRIPTIONS_L6 AS (
  SELECT DISTINCT
    CUS_CUST_ID_BUY
  FROM `meli-bi-data.WHOWNER.BT_MP_PAY_SUBSCRIPTION`
  WHERE SUB_STATUS IN ('active','ready')
    AND CUS_CUST_ID_SEL IN (797214326, 797215821, 797215856, 797215866, 797215778)
),
SUMMARY_MELIMAS AS (
  SELECT
    v.MONTH_ID,
    v.SIT_SITE_ID,
    v.PLATFORM_ACTUAL,
    COUNT(DISTINCT v.CUS_CUST_ID) AS TOTAL_VIEWERS,
    COUNT(DISTINCT s.CUS_CUST_ID_BUY) AS TOTAL_SUSCRIPTORES,
    SUM(v.TVM) AS TVM_TOTAL,
    SUM(CASE WHEN s.CUS_CUST_ID_BUY IS NOT NULL THEN v.TVM ELSE 0 END) AS TVM_TOTAL_MELIMAS
  FROM VIEWERS_PLATFORM_LABELLED v
  LEFT JOIN SUBSCRIPTIONS_L6 s
    ON v.CUS_CUST_ID = s.CUS_CUST_ID_BUY
  GROUP BY 1, 2, 3
)
SELECT *
FROM SUMMARY_MELIMAS
ORDER BY MONTH_ID, SIT_SITE_ID, PLATFORM_ACTUAL