-- VISITORS
DECLARE SITES ARRAY<STRING>;
DECLARE date_from DATE;
DECLARE date_to DATE;

SET SITES = ['MLA', 'MLB', 'MLM'];
SET date_from = '2025-04-01';
SET date_to = CURRENT_DATE();

WITH SESSIONS AS (
  SELECT
    s.SIT_SITE_ID,
    DATE_TRUNC(s.ds, WEEK(MONDAY)) AS fecha_week,
    DATE_TRUNC(s.ds, WEEK(THURSDAY)) AS fecha_week_thursday,
    EXTRACT(DAYOFWEEK FROM DS) AS day_week,
    s.ds,
    ORIGIN_PATH AS FIRST_EVENT_SOURCE,
    FIRST_TRACK AS FIRST_EVENT_PATH,
    FIRST_PLAY_DATETIME AS PLAY_TIMESTAMP,
    s.USER_ID,
    s.SESSION_ID AS MELIDATA_SESSION_ID,
    s.DEVICE_PLATFORM,
    IF(
      (
        (S.HAS_SEARCH IS TRUE OR S.HAS_VCP IS TRUE OR S.HAS_VCM IS TRUE OR HAS_PLAY IS TRUE) 
        OR TOTAL_FEED_IMPRESSIONS > 1
      ),
      TRUE,
      FALSE
    ) AS FLAG_VALID_VISIT,
    HAS_PLAY,
    S.TOTAL_SESSION_MILLISECOND/1000 AS session_time_sec
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS s
  WHERE s.ds >= date_from 
    AND s.ds < date_to
    AND s.SIT_SITE_ID IN UNNEST(SITES)
    AND LOWER(DEVICE_PLATFORM) LIKE '/tv%'
  GROUP BY ALL
),
SESSION_PLAY AS (
  SELECT DISTINCT
    s.SIT_SITE_ID,
    s.fecha_week,
    s.fecha_week_thursday,
    s.day_week,
    S.DS,
    s.FIRST_EVENT_SOURCE,
    s.FIRST_EVENT_PATH,
    s.PLAY_TIMESTAMP,
    s.USER_ID,
    s.MELIDATA_SESSION_ID,
    s.FLAG_VALID_VISIT,
    s.HAS_PLAY,
    EXTRACT(HOUR FROM P.START_PLAY_TIMESTAMP) AS HOUR_PLAY,
    CASE
      WHEN UPPER(s.DEVICE_PLATFORM) LIKE '%TIZEN%' THEN 'SAMSUNG'
      WHEN UPPER(s.DEVICE_PLATFORM) LIKE '%ANDR%' THEN 'ANDROID'
      WHEN UPPER(s.DEVICE_PLATFORM) LIKE '%WEB%' THEN 'LG'
    ELSE 'UNKNOWN'
    END AS DEVICE_PLATFORM,
    s.session_time_sec,
    SUM(P.PLAYBACK_TIME_MILLISECONDS/1000) AS TSV,
    SUM(P.PLAYBACK_TIME_MILLISECONDS/60000) AS TVM 
  FROM SESSIONS AS S 
  LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P 
    ON S.SIT_SITE_ID = P.SIT_SITE_ID
    AND s.USER_ID = P.USER_ID
    AND S.MELIDATA_SESSION_ID = P.SESSION_ID
    AND P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20                                               
  GROUP BY ALL
),
DOWNLOADS AS (
  SELECT 
    SIT_SITE_ID,
    DATE_TRUNC(DS, WEEK(MONDAY)) AS WEEK_ID,
    DS,
    PLATFORM,
    SUM (NET_APP_INSTALLS) AS DOWNLOADS
  FROM meli-bi-data.WHOWNER.BT_MKT_MPLAY_INSTALLS
  WHERE SIT_SITE_ID IN ('MLA','MLB','MLM','MLC','MCO','MPE','MLU','MEC')
  AND DS BETWEEN '2025-04-01' AND CURRENT_DATE()
  GROUP BY ALL
  ORDER BY DS
),
VIEWERS AS (
  SELECT DISTINCT
    P.SIT_SITE_ID,
    DS,
    DATE_TRUNC(DS, MONTH) AS MONTH_ID,
        CASE
      WHEN UPPER(DEVICE_PLATFORM) LIKE '%TIZEN%' THEN 'SAMSUNG'
      WHEN UPPER(DEVICE_PLATFORM) LIKE '%ANDR%' THEN 'ANDROID'
      WHEN UPPER(DEVICE_PLATFORM) LIKE '%WEB%' THEN 'LG'
    ELSE 'UNKNOWN'
    END AS PLATFORM,
    COUNT(DISTINCT P.USER_ID) AS VIEWERS_SMART,
    SUM(PLAYBACK_TIME_MILLISECONDS/60000) AS TVM_SMART
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` P
  LEFT JOIN  (
        select
        USER_ID,
        SIT_SITE_ID,
        MIN(DS) AS FIRST_DATE
        FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
        WHERE P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
        GROUP BY ALL
  ) AS FP ON FP.USER_ID = P.USER_ID AND FP.SIT_SITE_ID = P.SIT_SITE_ID
  WHERE LOWER(DEVICE_PLATFORM) LIKE '/tv%'
  AND DS BETWEEN '2025-04-01' AND CURRENT_DATE()
  AND PLAYBACK_TIME_MILLISECONDS/1000 >=20
  GROUP BY ALL
  ORDER BY MONTH_ID
)
SELECT 
  s.sit_site_id,
  s.fecha_week,
  CASE s.day_week
    WHEN 1 THEN 'Domingo'
    WHEN 2 THEN 'Lunes'
    WHEN 3 THEN 'Martes'
    WHEN 4 THEN 'Miércoles'
    WHEN 5 THEN 'Jueves'
    WHEN 6 THEN 'Viernes'
    WHEN 7 THEN 'Sábado'
  END AS week_day,
  s.ds,
  DATE_TRUNC(s.DS, MONTH) AS MONTH_ID,
  -- s.HOUR_PLAY,
  s.DEVICE_PLATFORM,
  d.DOWNLOADS,
  COUNT(DISTINCT s.USER_ID) AS Visitors,
  COUNT(DISTINCT CASE WHEN s.FLAG_VALID_VISIT IS TRUE THEN s.USER_ID ELSE NULL END) AS Valid_Visitors,
  v.VIEWERS_SMART,
  v.TVM_SMART,
  CONCAT(s.sit_site_id, '-', s.DEVICE_PLATFORM) AS site_platform,
  s.fecha_week_thursday
FROM SESSION_PLAY s
LEFT JOIN DOWNLOADS d ON s.DEVICE_PLATFORM = d.PLATFORM AND d.DS = s.DS AND d.SIT_SITE_ID = s.SIT_SITE_ID
LEFT JOIN VIEWERS v ON s.DEVICE_PLATFORM = v.PLATFORM AND v.DS = s.DS AND v.SIT_SITE_ID = s.SIT_SITE_ID
GROUP BY ALL
ORDER BY ds DESC;
