DECLARE SITES ARRAY<STRING>;
DECLARE date_from DATE;
DECLARE date_to DATE;
SET SITES = ['MLC', 'MLA', 'MLB', 'MLM', 'MCO', 'MPE', 'MLU', 'MEC'];
SET date_from = '2025-03-03';
SET date_to = current_date();

WITH SESSIONS AS
  ( SELECT
      s.SIT_SITE_ID,
      DATE_TRUNC(s.ds, MONTH) as MONTH_ID,
      DATE_TRUNC(s.ds, WEEK(MONDAY)) as fecha_week,
      s.ds,
      ORIGIN_PATH AS FIRST_EVENT_SOURCE,
      FIRST_TRACK AS FIRST_EVENT_PATH,
      FIRST_PLAY_DATETIME AS PLAY_TIMESTAMP,
      s.USER_ID,
      s.SESSION_ID AS MELIDATA_SESSION_ID,
      s.DEVICE_PLATFORM,
      IF(((S.HAS_SEARCH IS TRUE OR S.HAS_VCP IS TRUE OR S.HAS_VCM IS TRUE OR HAS_PLAY IS TRUE) OR TOTAL_FEED_IMPRESSIONS > 1),TRUE,FALSE) AS FLAG_VALID_VISIT,
      HAS_PLAY,
      S.TOTAL_SESSION_MILLISECOND/1000 AS session_time_sec
    FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION` AS s
    WHERE s.ds >= date_from 
    AND s.ds < date_to
    AND s.SIT_SITE_ID IN UNNEST(SITES)
    GROUP BY ALL
  )
, SESSION_PLAY AS   ( 
    SELECT DISTINCT
      s.SIT_SITE_ID,
      s.MONTH_ID,
      s.fecha_week,
      S.DS,
      s.FIRST_EVENT_SOURCE,
      s.FIRST_EVENT_PATH,
      s.PLAY_TIMESTAMP,
      s.USER_ID,
      s.MELIDATA_SESSION_ID,
      s.FLAG_VALID_VISIT,
      s.HAS_PLAY,
      s.DEVICE_PLATFORM,
      s.session_time_sec,
      SUM(P.PLAYBACK_TIME_MILLISECONDS/1000) AS TSV,
      SUM(P.PLAYBACK_TIME_MILLISECONDS/60000) AS TVM 
    FROM SESSIONS AS S 
    LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P ON S.SIT_SITE_ID = P.SIT_SITE_ID
      AND s.USER_ID = P.USER_ID
      AND S.MELIDATA_SESSION_ID = P.SESSION_ID
      AND P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20                                               
    GROUP BY ALL
),
NEW_RET_RECO AS (
    SELECT 
        *
      , DATE_TRUNC(DS,DAY) AS TIME_FRAME_ID
      , LAG(DS,1)OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY START_PLAY_TIMESTAMP ASC) AS DS_ANT 
      , (CASE WHEN (LAG(DS,1)OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)) IS NULL THEN 'NEW' 
      WHEN DATE_DIFF(DS, (LAG(DS,1)OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)), DAY) <= 30 THEN 'RETAINED'
      WHEN DATE_DIFF(DS, (LAG(DS,1)OVER(PARTITION BY SIT_SITE_ID,USER_ID ORDER BY START_PLAY_TIMESTAMP ASC)), DAY) > 30  THEN 'RECOVERED' ELSE NULL END) AS FLAG_N_R
    FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
    WHERE  PLAYBACK_TIME_MILLISECONDS/1000 >= 20 
      AND DS <= CURRENT_DATE-1
  ),
  ATTR_TIME_FRAME_ELEGIDO AS (
          SELECT
          SESSION_ID,
          SIT_SITE_ID,
          USER_ID,
          TIME_FRAME_ID,
          FLAG_N_R
          FROM NEW_RET_RECO
          QUALIFY ROW_NUMBER()  OVER(PARTITION BY SIT_SITE_ID,USER_ID, TIME_FRAME_ID ORDER BY START_PLAY_TIMESTAMP ASC) =  1
  ),
  CRUCE_FLAG AS (
          SELECT
          A.*,
          E.FLAG_N_R AS FLAG_N_R_FINAL
          FROM NEW_RET_RECO AS A
          LEFT JOIN ATTR_TIME_FRAME_ELEGIDO AS E ON E.SIT_SITE_ID = A.SIT_SITE_ID AND E.USER_ID = A.USER_ID AND E.TIME_FRAME_ID = A.TIME_FRAME_ID
  )
SELECT 
  s.sit_site_id,
  DATE_TRUNC(s.DS, MONTH) AS MONTH_ID,
  DATE_TRUNC(s.DS, WEEK(MONDAY)) as WEEK_ID,
  CASE WHEN S.DEVICE_PLATFORM IN ('/tv/android') THEN '/tv/android'
    WHEN S.DEVICE_PLATFORM IN ('/tv/Tizen') THEN '/tv/Tizen'
    WHEN S.DEVICE_PLATFORM IN ('/tv/Web0S') THEN '/tv/Web0S'
    ELSE COALESCE(o.SOURCE_TYPE,'Otros')
    END AS Origin,
  US.FLAG_N_R_FINAL,
  CONCAT(o.SOURCE_SESSION_L1,'-', o.SOURCE_SESSION_L2, '-', o.TEAM) AS touchpoint,
  o.SOURCE_SESSION_L1 AS Clasificacion,
  o.SOURCE_SESSION_L2 AS Clasificacion_2,
  o.TEAM AS Team,
  COUNT(DISTINCT s.melidata_session_id) Sessions,
  COUNT(DISTINCT CASE WHEN s.FLAG_VALID_VISIT IS TRUE THEN s.melidata_session_id ELSE NULL END) as Sessions_valid_visit,
  COUNT(DISTINCT CASE WHEN s.TSV >= 20 THEN s.melidata_session_id ELSE NULL END) as Sessions_valid_view,
  ROUND(SUM(s.TVM), 2) as TVM,
  COUNT(DISTINCT s.USER_ID) Visitors,
  COUNT(DISTINCT CASE WHEN s.FLAG_VALID_VISIT IS TRUE THEN s.USER_ID ELSE NULL END) as Valid_Visitors,
  COUNT(DISTINCT CASE WHEN s.TSV >= 20 THEN s.USER_ID ELSE NULL END) as Viewers,
  COUNT(DISTINCT US.USER_ID) AS total_users
FROM SESSION_PLAY s
LEFT JOIN `meli-sbox.MPLAY.LK_MPLAY_SOURCE_TYPE_ORIGIN_SESSION` o on coalesce(s.FIRST_EVENT_SOURCE,'NULL') = coalesce(o.SOURCE_TYPE,'NULL')
LEFT JOIN CRUCE_FLAG US ON US.SESSION_ID = s.MELIDATA_SESSION_ID
GROUP BY ALL
ORDER BY WEEK_ID ASC
;
