with matt_total_channel_month as (
  SELECT
    M.SIT_SITE_ID,
    COALESCE(c.user_id, S.USER_ID) AS USER_ID,
    date_trunc(CONVERSION_CREATED_DATE, month) as month_id,
    case
      when (MATT_PLAYER is not null and MATT_PLAYER != '') then MATT_PLAYER
      else MATT_TYPE_SOURCE
    end as channel,
    ROUND(SUM(MATT_PORC_LAST_CLICK / 100.0)) SUM_MATT
  from
    `growth-attribution.production.BT_MATT_FINE_TUNED_MERCADOPLAY` as m
    left join `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_PLAY` as C on C.FIRST_PLAY_HASH_ID = M.CONVERSION_ID
    and M.CONVERSION_CREATED_DATE <= DATE'2024-10-31'
    left join `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_SESSION` as S on S.FIRST_SESSION_HASH_ID = M.CONVERSION_ID
    and M.CONVERSION_CREATED_DATE >= DATE'2024-11-01'
  GROUP BY
    ALL
),
TOTAL_X_USER AS (
  SELECT
    M.SIT_SITE_ID,
    M.USER_ID,
    M.MONTH_ID,
    M.CHANNEL,
    M.SUM_MATT / SUM(SUM_MATT) OVER (
      PARTITION BY
        M.SIT_SITE_ID,
        M.USER_ID,
        M.MONTH_ID
    ) AS ATTR_USER
  FROM
    matt_total_channel_month AS M
)
SELECT
  T.MONTH_ID,
  CASE
    WHEN F.USER_ID IS NOT NULL THEN 'NEW'
    ELSE 'OLD'
  END AS FLAG_USER,
  T.SIT_SITE_ID,
  T.CHANNEL,
  SUM(ATTR_USER) AS TOTAL_USERS,
  SUM(
    CASE
      WHEN F.FLAG_RET = 1 THEN ATTR_USER
      ELSE NULL
    END
  ) AS TOTAL_USERS_RETENTION,
  SUM(
    CASE
      WHEN F.TOTAL_DAYS_DISTINCT >= 2 THEN ATTR_USER
      ELSE NULL
    END
  ) AS TOTAL_USERS_AHA_MOMENT,
from
  TOTAL_X_USER AS T
  left join (
    SELECT
      A.*,
      MAX(
        CASE
          WHEN P.USER_ID IS NOT NULL THEN 1
          ELSE 0
        END
      ) AS FLAG_RET,
      COUNT(DISTINCT P.DS) AS TOTAL_DAYS_DISTINCT
    FROM
      (
        select
          sit_site_id,
          user_id,
          min(ds) as fecha_new,
        from
          `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` as P
        where
          p.PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
        group by
          all
      ) A
      LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P ON A.SIT_SITE_ID = P.SIT_SITE_ID
      AND A.USER_ID = P.USER_ID
      AND P.DS BETWEEN A.FECHA_NEW + 1 AND A.FECHA_NEW + 30
      AND P.PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    GROUP BY
      ALL
  ) as F on F.sit_site_id = T.sit_site_id
  and F.user_id = T.USER_ID
  AND DATE_TRUNC(F.fecha_new, MONTH) = T.MONTH_ID
GROUP BY
  ALL







-- ====================================================
---------------------- LC AHA V2 -------------------
-- ====================================================
WITH DATA_USERS AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    DS,
    SUM(PLAYBACK_TIME_MILLISECONDS/60000) AS TVM,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_DESKTOP
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20
    AND DS <= CURRENT_DATE - 1
  GROUP BY ALL
),

TABLE_CALENDAR AS (
  SELECT DISTINCT
    DATE_TRUNC(TIM_DAY, MONTH) AS MONTH_ID,
    SIT_SITE_ID,
    USER_ID,
    SUM(TVM) AS TVM,
    SUM(TOTAL_TV) AS TVM_TV,
    SUM(TOTAL_MOBILE) AS TVM_MOBILE,
    SUM(TOTAL_DESKTOP) AS TVM_DESKTOP
  FROM DATA_USERS AS A
  INNER JOIN `meli-bi-data.WHOWNER.LK_TIM_DAYS` AS TD
    ON A.DS BETWEEN TD.TIM_DAY - 29 AND TD.TIM_DAY
  WHERE TD.TIM_DAY >= DATE'2025-01-01'
  GROUP BY ALL
),

PLATFORM_DATA AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    MONTH_ID,
    CONCAT(
      CASE WHEN TVM_TV > 0 THEN 'SMART' ELSE '' END, ' - ',
      CASE WHEN TVM_MOBILE > 0 THEN 'MOBILE' ELSE '' END, ' - ',
      CASE WHEN TVM_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END
    ) AS PLATFORM_CONCAT
  FROM TABLE_CALENDAR
),

-- MATT con Channel
MATT_TOTAL_CHANNEL_MONTH AS (
  SELECT
    M.SIT_SITE_ID,
    COALESCE(c.user_id, S.USER_ID) AS USER_ID,
    DATE_TRUNC(CONVERSION_CREATED_DATE, MONTH) AS MONTH_ID,
    CASE 
      WHEN (MATT_PLAYER IS NOT NULL AND MATT_PLAYER != '') 
        THEN MATT_PLAYER 
      ELSE MATT_TYPE_SOURCE 
    END AS CHANNEL,
    ROUND(SUM(MATT_PORC_LAST_CLICK/100.0)) AS SUM_MATT
  FROM growth-attribution.production.BT_MATT_FINE_TUNED_MERCADOPLAY AS M
  LEFT JOIN `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_PLAY` AS C 
    ON C.first_play_hash_id = M.CONVERSION_ID
    AND M.CONVERSION_CREATED_DATE <= DATE'2024-10-31'
  LEFT JOIN `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_SESSION` AS S 
    ON S.FIRST_SESSION_HASH_ID = M.CONVERSION_ID
    AND M.CONVERSION_CREATED_DATE >= DATE'2024-11-01'
  GROUP BY ALL  
),

TOTAL_X_USER AS (
  SELECT
    M.SIT_SITE_ID,
    M.USER_ID,
    M.MONTH_ID,
    M.CHANNEL,
    M.SUM_MATT / SUM(SUM_MATT) OVER (PARTITION BY M.SIT_SITE_ID, M.USER_ID, M.MONTH_ID) AS ATTR_USER
  FROM MATT_TOTAL_CHANNEL_MONTH AS M
),

RETENTION_DATA AS (
  SELECT
    A.*,
    MAX(CASE WHEN P.USER_ID IS NOT NULL THEN 1 ELSE 0 END) AS FLAG_RET,
    COUNT(DISTINCT P.DS) AS TOTAL_DAYS_DISTINCT
  FROM (
    SELECT
      SIT_SITE_ID,
      USER_ID,
      MIN(DS) AS FECHA_NEW
    FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
    WHERE P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
    GROUP BY ALL
  ) A
  LEFT JOIN `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P 
    ON A.SIT_SITE_ID = P.SIT_SITE_ID
    AND A.USER_ID = P.USER_ID
    AND P.DS BETWEEN A.FECHA_NEW + 1 AND A.FECHA_NEW + 30
    AND P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
  GROUP BY ALL
)

-- Query Final AHA + Retention + Platform
SELECT
  T.MONTH_ID,
  CASE WHEN F.USER_ID IS NOT NULL THEN 'NEW' ELSE 'OLD' END AS FLAG_USER,
  T.SIT_SITE_ID,
  T.CHANNEL,
  P.PLATFORM_CONCAT,
  SUM(ATTR_USER) AS TOTAL_USERS,
  SUM(CASE WHEN F.FLAG_RET = 1 THEN ATTR_USER ELSE NULL END) AS TOTAL_USERS_RETENTION,
  SUM(CASE WHEN F.TOTAL_DAYS_DISTINCT >= 2 THEN ATTR_USER ELSE NULL END) AS TOTAL_USERS_AHA_MOMENT
FROM TOTAL_X_USER AS T
LEFT JOIN RETENTION_DATA AS F 
  ON F.SIT_SITE_ID = T.SIT_SITE_ID
  AND F.USER_ID = T.USER_ID
  AND DATE_TRUNC(F.FECHA_NEW, MONTH) = T.MONTH_ID
LEFT JOIN PLATFORM_DATA AS P
  ON P.SIT_SITE_ID = T.SIT_SITE_ID
  AND P.USER_ID = T.USER_ID
  AND P.MONTH_ID = T.MONTH_ID
GROUP BY ALL;