-- description: Retención y churn de usuarios a 30 días con atribución de canal y segmentación por plataforma y rango de minutos reproducidos.
-- domain: behaviour
-- product: mplay
-- use_case: retention / churn_analysis / channel_attribution
-- grain: SIT_SITE_ID, USER_ID, TIM_DAY
-- time_grain: daily
-- date_column: DS / TIM_DAY
-- date_filter: between
-- threshold_rule: PLAYBACK_TIME_MILLISECONDS >= 20000
-- metrics:
-- - TVM: minutos reproducidos por usuario en el periodo
-- - TOTAL_ACTIVE_TIM_DAY: cantidad de usuarios activos en el día
-- - TOTAL_RETENTION_TIM_DAY_CHURN: cantidad de usuarios retenidos 30 días después
-- - CHANNEL: canal atribuido al usuario
-- tables_read:
-- - WHOWNER.BT_MKT_MPLAY_PLAYS
-- - WHOWNER.LK_TIM_DAYS
-- - growth-attribution.production.BT_MATT_FINE_TUNED_MERCADOPLAY
-- - WHOWNER.LK_MPLAY_FIRST_PLAY
-- - WHOWNER.LK_MPLAY_FIRST_SESSION
-- joins:
-- - DATA_USERS INNER JOIN LK_TIM_DAYS ON DS BETWEEN TIM_DAY-29 AND TIM_DAY
-- - TABLE_CALENDAR LEFT JOIN TABLE_CALENDAR (self-join) para cálculo de retention 30 días
-- - LEFT JOIN FIRST_CHANNEL_DAILY ON SIT_SITE_ID, USER_ID, DS
-- owner: data_team

WITH DATA_USERS AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    DS,
    SUM(PLAYBACK_TIME_MILLISECONDS/60000) AS TVM,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_DESKTOP
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20
    AND DS <= CURRENT_DATE - 1
  GROUP BY ALL
),

-- =========================================
-- 2) Tabla calendario para Retention Churn
-- =========================================
TABLE_CALENDAR AS (
  SELECT DISTINCT
    TIM_DAY,
    TIM_DAY + 30 AS TIM_DAY_CHURN,
    SIT_SITE_ID,
    USER_ID,
    SUM(TVM) AS TVM,
    SUM(TOTAL_TV) AS TVM_TV,
    SUM(TOTAL_MOBILE) AS TVM_MOBILE,
    SUM(TOTAL_DESKTOP) AS TVM_DESKTOP
  FROM DATA_USERS AS A
  INNER JOIN `meli-bi-data.WHOWNER.LK_TIM_DAYS` AS TD
    ON A.DS BETWEEN TD.TIM_DAY - 29 AND TD.TIM_DAY
  WHERE TD.TIM_DAY >= DATE'2025-01-01'
  GROUP BY ALL
),

-- =========================================
-- 3) Primera atribución diaria (Channel)
-- =========================================
FIRST_CHANNEL_DAILY AS (
  SELECT
    m.SIT_SITE_ID,
    COALESCE(c.USER_ID, s.USER_ID) AS USER_ID,
    DATE(m.CONVERSION_CREATED_DATE) AS DS,
    CASE
      WHEN (MATT_PLAYER IS NOT NULL AND MATT_PLAYER != '') THEN MATT_PLAYER
      ELSE MATT_TYPE_SOURCE
    END AS CHANNEL
  FROM `growth-attribution.production.BT_MATT_FINE_TUNED_MERCADOPLAY` AS m
  LEFT JOIN `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_PLAY` AS c
    ON c.FIRST_PLAY_HASH_ID = m.CONVERSION_ID
    AND m.CONVERSION_CREATED_DATE <= DATE'2024-10-31'
  LEFT JOIN `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_SESSION` AS s
    ON s.FIRST_SESSION_HASH_ID = m.CONVERSION_ID
    AND m.CONVERSION_CREATED_DATE >= DATE'2024-11-01'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY SIT_SITE_ID, COALESCE(c.USER_ID, s.USER_ID), DATE(m.CONVERSION_CREATED_DATE)
    ORDER BY m.CONVERSION_CREATED_DATE ASC
  ) = 1
)

-- ========================
-- 4) Query final Retention + Channel
-- ========================
SELECT
  T.TIM_DAY,
  T.TIM_DAY_CHURN,
  T.SIT_SITE_ID,
  CASE
    WHEN SAFE_CAST(T.USER_ID AS INT64) IS NULL THEN 'not_log'
    ELSE 'log'
  END AS FLAG_USER,
  CONCAT(
    CASE WHEN T.TVM_TV > 0 THEN 'SMART' ELSE '' END, ' - ',
    CASE WHEN T.TVM_MOBILE > 0 THEN 'MOBILE' ELSE '' END, ' - ',
    CASE WHEN T.TVM_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END
  ) AS PLATFORM_CONCAT,
  CASE
    WHEN T.TVM < 3 THEN 'A. MENOR A 3 MIN'
    WHEN T.TVM BETWEEN 3 AND 10 THEN 'B. ENTRE 3 Y 10 MIN'
    WHEN T.TVM BETWEEN 10 AND 30 THEN 'C. ENTRE 10 Y 30 MIN'
    ELSE 'D. MAYOR A 30 MIN'
  END AS RANGE_TVM_TIMEFRAME,
  COUNT(DISTINCT T.USER_ID) AS TOTAL_ACTIVE_TIM_DAY,
  COUNT(DISTINCT T2.USER_ID) AS TOTAL_RETENTION_TIM_DAY_CHURN,
  fcd.CHANNEL
FROM TABLE_CALENDAR AS T
LEFT JOIN TABLE_CALENDAR AS T2
  ON T2.SIT_SITE_ID = T.SIT_SITE_ID
  AND T2.USER_ID = T.USER_ID
  AND T2.TIM_DAY = T.TIM_DAY_CHURN
LEFT JOIN FIRST_CHANNEL_DAILY AS fcd
  ON fcd.SIT_SITE_ID = T.SIT_SITE_ID
  AND fcd.USER_ID = T.USER_ID
  AND fcd.DS = T.TIM_DAY
GROUP BY ALL;