with matt_total_channel_month as (
SELECT
M.SIT_SITE_ID,
COALESCE(c.user_id,S.USER_ID) AS USER_ID,
date_trunc(CONVERSION_CREATED_DATE,month) as month_id,
case when (MATT_PLAYER is not null and MATT_PLAYER !='') then MATT_PLAYER else MATT_TYPE_SOURCE end as channel,
ROUND(SUM(MATT_PORC_LAST_CLICK/100.0)) SUM_MATT
from growth-attribution.production.BT_MATT_FINE_TUNED_MERCADOPLAY as m
left join `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_PLAY` as C ON C.first_play_hash_id = M.CONVERSION_ID
                                                          AND M.CONVERSION_CREATED_DATE <= DATE'2024-10-31'
left join `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_SESSION` as S ON S.FIRST_SESSION_HASH_ID = M.CONVERSION_ID
                                                          AND M.CONVERSION_CREATED_DATE >= DATE'2024-11-01'

GROUP BY ALL  
),

TOTAL_X_USER AS (

SELECT
M.SIT_SITE_ID,
M.USER_ID,
M.MONTH_ID,
M.CHANNEL,
M.SUM_MATT/SUM(SUM_MATT) OVER (PARTITION BY M.SIT_SITE_ID,M.USER_ID,M.MONTH_ID) AS ATTR_USER
FROM matt_total_channel_month AS M
)

SELECT
T.MONTH_ID,
CASE WHEN F.USER_ID IS NOT NULL THEN 'NEW' ELSE 'OLD' END AS FLAG_USER,
T.SIT_SITE_ID,
T.CHANNEL,
SUM(ATTR_USER) AS TOTAL_USERS,
SUM(CASE WHEN F.FLAG_RET = 1 THEN ATTR_USER ELSE NULL END) AS TOTAL_USERS_RETENTION,
SUM(CASE WHEN F.TOTAL_DAYS_DISTINCT >= 2 THEN ATTR_USER ELSE NULL END) AS TOTAL_USERS_AHA_MOMENT,

from TOTAL_X_USER AS T

left join(
SELECT
A.*,
MAX(CASE WHEN P.USER_ID IS NOT NULL THEN 1 ELSE 0 END) AS FLAG_RET,
COUNT(DISTINCT P.DS) AS TOTAL_DAYS_DISTINCT
FROM (
select
sit_site_id,
user_id,
min(ds) as fecha_new,
from `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` as P
where p.PLAYBACK_TIME_MILLISECONDS/1000>=20
group by all
) A
LEFT JOIN WHOWNER.BT_MKT_MPLAY_PLAYS AS P ON A.SIT_SITE_ID = P.SIT_SITE_ID
AND A.USER_ID = P.USER_ID
AND P.DS BETWEEN A.FECHA_NEW+1 AND A.FECHA_NEW+30
AND P.PLAYBACK_TIME_MILLISECONDS/1000 >= 20
GROUP BY ALL
)
as F on F.sit_site_id = T.sit_site_id
and F.user_id = T.USER_ID
AND DATE_TRUNC(F.fecha_new,MONTH) = T.MONTH_ID

GROUP BY ALL