WITH PLAY_DAYS AS (
  SELECT DISTINCT
    P.SIT_SITE_ID AS SIT_SITE_ID,
    P.USER_ID AS USER_ID,
    P.DS AS DAY_PLAY,
    SUM(P.PLAYBACK_TIME_MILLISECONDS / 60000) AS PLAYBACK_TIME,
    SUM(CASE WHEN UPPER(P.DEVICE_PLATFORM) LIKE '%TV%' THEN P.PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN UPPER(P.DEVICE_PLATFORM) LIKE '%MOBILE%' THEN P.PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(P.DEVICE_PLATFORM) LIKE '%DESK%' THEN P.PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_DESKTOP
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` AS P
  WHERE P.PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
  GROUP BY ALL
),

PLAY_FIRST_DAY AS ( 
  SELECT 
    SIT_SITE_ID,
    USER_ID,
    MIN(DAY_PLAY) AS FIRST_DAY
  FROM PLAY_DAYS
  GROUP BY ALL
),

TABLE_CALENDAR AS (
  SELECT
    *
  FROM (
    SELECT 
      *,
      ROW_NUMBER() OVER (PARTITION BY FECHA_COHORT ORDER BY FECHA_INI ASC) AS MONTH_NUMBER
    FROM (
      SELECT 
        T.TIM_DAY AS FECHA_COHORT,
        T2.TIM_DAY - 29 AS FECHA_INI,
        T2.TIM_DAY AS FECHA_FIN
      FROM `meli-bi-data.WHOWNER.LK_TIM_DAYS` AS T
      LEFT JOIN `meli-bi-data.WHOWNER.LK_TIM_DAYS` AS T2 
        ON T.TIM_DAY + 1 <= T2.TIM_DAY
      -- +1 PARA SACAR DIA DE ALTA
      WHERE T.TIM_DAY >= DATE_TRUNC(DATE_SUB(CURRENT_DATE, INTERVAL 18 MONTH), MONTH)
      QUALIFY MOD(ROW_NUMBER() OVER (PARTITION BY T.TIM_DAY ORDER BY T2.TIM_DAY ASC), 30) = 0
    ) AS A
    WHERE FECHA_FIN <= DATE_TRUNC(CURRENT_DATE - 1, MONTH) - 1
  ) AS B
  QUALIFY COUNT(FECHA_FIN) OVER (
    PARTITION BY DATE_TRUNC(FECHA_COHORT, MONTH), MONTH_NUMBER
  ) = EXTRACT(DAY FROM (LAST_DAY(FECHA_COHORT)))
  -- COHORT_HASTA AYER
),

USERS_CALENDAR AS (
  SELECT 
    PF.*,
    T.FECHA_INI,
    T.FECHA_FIN,
    MONTH_NUMBER
  FROM PLAY_FIRST_DAY AS PF
  LEFT JOIN TABLE_CALENDAR AS T 
    ON PF.FIRST_DAY = T.FECHA_COHORT 
),

MATT_TOTAL_CHANNEL_MONTH_DEDUP AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    MONTH_ID,
    CHANNEL
  FROM (
    SELECT
      M.SIT_SITE_ID,
      COALESCE(c.user_id, S.USER_ID) AS USER_ID,
      DATE_TRUNC(CONVERSION_CREATED_DATE, MONTH) AS MONTH_ID,
      CASE 
        WHEN (MATT_PLAYER IS NOT NULL AND MATT_PLAYER != '') 
          THEN MATT_PLAYER 
        ELSE MATT_TYPE_SOURCE 
      END AS CHANNEL,
      ROW_NUMBER() OVER(PARTITION BY COALESCE(c.user_id, S.USER_ID), M.SIT_SITE_ID, DATE_TRUNC(CONVERSION_CREATED_DATE, MONTH) ORDER BY CONVERSION_CREATED_DATE) AS rn
    FROM growth-attribution.production.BT_MATT_FINE_TUNED_MERCADOPLAY AS M
    LEFT JOIN `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_PLAY` AS C 
      ON C.first_play_hash_id = M.CONVERSION_ID
      AND M.CONVERSION_CREATED_DATE <= DATE'2024-10-31'
    LEFT JOIN `meli-bi-data.WHOWNER.LK_MPLAY_FIRST_SESSION` AS S 
      ON S.FIRST_SESSION_HASH_ID = M.CONVERSION_ID
      AND M.CONVERSION_CREATED_DATE >= DATE'2024-11-01'
  )
  WHERE rn = 1
),

BASE AS (
  SELECT
    *,
    CASE 
      WHEN FLAG_TVM > 0 
        AND ROW_NUMBER() OVER (PARTITION BY SIT_SITE_ID, USER_ID, FLAG_TVM ORDER BY MONTH_NUMBER ASC) = MONTH_NUMBER
      THEN 'ALL_MONTH' 
      ELSE 'NOT_RECURRENT' 
    END AS FLAG_CONSEC,
    COUNT(DISTINCT USER_ID || SIT_SITE_ID) OVER (PARTITION BY MONTH_COHORT_ACQ, SIT_SITE_ID) AS TOTAL_USERS_COHORT
  FROM (
    SELECT
      U.USER_ID,
      U.SIT_SITE_ID,
      U.MONTH_NUMBER,
      DATE_TRUNC(U.FIRST_DAY, MONTH) AS MONTH_COHORT_ACQ,
      SUM(P.PLAYBACK_TIME) AS TVM,
      SUM(P.TOTAL_TV) AS TVM_TV,
      SUM(P.TOTAL_MOBILE) AS TVM_MOBILE,
      SUM(P.TOTAL_DESKTOP) AS TVM_DESKTOP,
      CASE WHEN SUM(P.PLAYBACK_TIME) > 0 THEN 1 ELSE 0 END AS FLAG_TVM,
      COALESCE(C.CHANNEL, 'UNKNOWN') AS CHANNEL
    FROM USERS_CALENDAR AS U
    LEFT JOIN PLAY_DAYS AS P 
      ON U.USER_ID = P.USER_ID
      AND U.SIT_SITE_ID = P.SIT_SITE_ID
      AND P.DAY_PLAY BETWEEN U.FECHA_INI AND U.FECHA_FIN
    LEFT JOIN MATT_TOTAL_CHANNEL_MONTH_DEDUP AS C
      ON U.SIT_SITE_ID = C.SIT_SITE_ID
      AND U.USER_ID = C.USER_ID
      AND C.MONTH_ID = DATE_TRUNC(U.FIRST_DAY, MONTH)
    GROUP BY ALL
  )
)

SELECT 
  SIT_SITE_ID,
  MONTH_COHORT_ACQ,
  MONTH_NUMBER - 1 AS MONTH_RETENTION,
  TOTAL_USERS_COHORT AS TOTAL_USERS_COHORT,
  COUNT(DISTINCT CASE WHEN TVM > 0 THEN USER_ID || SIT_SITE_ID ELSE NULL END) AS TOTAL_USERS_RETENTION,
  SUM(TVM) AS TVM,
  SUM(TVM_TV) AS TVM_TV,
  SUM(TVM_MOBILE) AS TVM_MOBILE,
  SUM(TVM_DESKTOP) AS TVM_DESKTOP,
  CONCAT(
    CASE WHEN SUM(TVM_TV) > 0 THEN 'SMART' ELSE '' END,
    CASE WHEN SUM(TVM_TV) > 0 AND (SUM(TVM_MOBILE) > 0 OR SUM(TVM_DESKTOP) > 0) THEN ' - ' ELSE '' END,
    CASE WHEN SUM(TVM_MOBILE) > 0 THEN 'MOBILE' ELSE '' END,
    CASE WHEN SUM(TVM_MOBILE) > 0 AND SUM(TVM_DESKTOP) > 0 THEN ' - ' ELSE '' END,
    CASE WHEN SUM(TVM_DESKTOP) > 0 THEN 'DESKTOP' ELSE '' END
  ) AS PLATFORM_CONCAT,
  CHANNEL,
  COUNT(DISTINCT CASE WHEN TVM > 0 AND FLAG_CONSEC = 'ALL_MONTH' THEN USER_ID || SIT_SITE_ID ELSE NULL END) AS ALL_MONTH_USER_RET,
  SUM(CASE WHEN TVM > 0 AND FLAG_CONSEC = 'ALL_MONTH' THEN TVM ELSE NULL END) AS ALL_MONTH_TVM
FROM BASE
WHERE MONTH_NUMBER IS NOT NULL
GROUP BY ALL