-- `EXPLOTACION.LYL_LCM_RETENTION_CHURN_30_DAYS`

WITH DATA_USERS AS (
SELECT
SIT_SITE_ID,
USER_ID,
DS,
SUM(PLAYBACK_TIME_MILLISECONDS/60000) AS TVM,
SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_TV,
SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_MOBILE,
SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS/60000 ELSE 0 END) AS TOTAL_DESKTOP,

FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`

WHERE PLAYBACK_TIME_MILLISECONDS/1000 >= 20
AND DS <= CURRENT_DATE-1
GROUP BY ALL
),

TABLE_CALENDAR AS (


SELECT DISTINCT
TIM_DAY,
TIM_DAY+30 AS TIM_DAY_CHURN,
SIT_SITE_ID,
USER_ID,
SUM(TVM) AS TVM,
SUM(TOTAL_TV) AS TVM_TV,
SUM(TOTAL_MOBILE) AS TVM_MOBILE,
SUM(TOTAL_DESKTOP) AS TVM_DESKTOP,
FROM DATA_USERS AS A
INNER JOIN `meli-bi-data.WHOWNER.LK_TIM_DAYS` as TD ON A.DS BETWEEN TD.TIM_DAY-29 AND TD.TIM_DAY
WHERE TD.TIM_DAY >= DATE'2025-01-01'
-- AND TD.TIM_DAY = LAST_DAY(TD.TIM_DAY)
GROUP BY ALL
)
/*
31-05 --> 02-05 AND 31-05
30-06 --> 01-06 AND 30-06
*/

SELECT
T.TIM_DAY,
T.TIM_DAY_CHURN,
T.SIT_SITE_ID,
case when safe_cast(T.user_id as int64)is null then 'not_log' else 'log' end as flag_user,
CONCAT( CASE WHEN T.TVM_TV > 0 THEN 'SMART' ELSE '' END ,' - ',
CASE WHEN T.TVM_MOBILE > 0 THEN 'MOBILE' ELSE '' END ,' - ',
CASE WHEN T.TVM_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END ) AS PLATFORM_CONCAT,
CASE WHEN T.TVM < 3 THEN 'A. MENOR A 3 MIN'
WHEN T.TVM BETWEEN 3 AND 10 THEN 'B. ENTRE 3 Y 10 MIN'
WHEN T.TVM BETWEEN 10 AND 30 THEN 'C. ENTRE 10 Y 30 MIN'
ELSE 'D. MAYOR A 30 MIN' END AS RANGE_TVM_TIMEFRAME,
COUNT(DISTINCT T.USER_ID) AS TOTAL_ACTIVE_TIM_DAY,
COUNT(DISTINCT T2.USER_ID) AS TOTAL_RETENTION_TIM_DAY_CHURN

FROM TABLE_CALENDAR AS T
LEFT JOIN TABLE_CALENDAR AS T2 ON T2.SIT_SITE_ID = T.SIT_SITE_ID
AND T2.USER_ID = T.USER_ID
AND T2.TIM_DAY = T.TIM_DAY_CHURN
GROUP BY ALL






