WITH BUYERS_MARKETPLACE AS (
  SELECT DISTINCT 
    DATE_TRUNC(bd.ord_created_dt, MONTH) AS MONTH_ID,
    bd.sit_site_id AS SIT_SITE_ID,
    CAST(bd.ord_buyer.id AS STRING) AS USER_ID
  FROM `meli-bi-data.WHOWNER.BT_ORD_ORDERS` AS bd
  WHERE bd.ord_tgmv_flg = TRUE
    AND COALESCE(bd.ord_auto_offer_flg, FALSE) = FALSE
    AND bd.sit_site_id IN ('MLA','MLM','MLC','MCO','MLU','MPE','MLB', 'MEC')
    AND bd.ord_closed_dt IS NOT NULL
    AND bd.ord_category.marketplace_id = 'TM'
    AND ord_order_mshops_flg = FALSE
    AND ord_order_proximity_flg = FALSE
    AND bd.ord_created_dt >= '2023-01-01'
),
VIEWERS_PLATFORM AS (
  SELECT
    DATE_TRUNC(DS, MONTH) AS MONTH_ID,
    SIT_SITE_ID,
    CAST(USER_ID AS STRING) AS USER_ID,
    CUS_CUST_ID,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_DESKTOP,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%CAST%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_CAST
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND DS <= CURRENT_DATE() - 1
  GROUP BY 1, 2, 3, 4
),
VIEWERS_PLATFORM_LABELLED AS (
  SELECT
    MONTH_ID,
    SIT_SITE_ID,
    USER_ID,
    CUS_CUST_ID,
    CASE
      WHEN ROUND(TVM_TOTAL_TIMEFRAME, 2) = ROUND(TOTAL_CAST, 2) AND TOTAL_CAST > 0 THEN 'CAST' 
      ELSE CONCAT(
        CASE WHEN TOTAL_TV > 0 THEN 'SMART' ELSE '' END ,'',
        CASE WHEN TOTAL_MOBILE > 0 THEN 'MOBILE' ELSE '' END ,'',
        CASE WHEN TOTAL_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END ,'',
        CASE WHEN TOTAL_CAST > 0 THEN 'CAST' ELSE '' END
      ) END AS PLATFORM_ACTUAL
  FROM VIEWERS_PLATFORM
),
SUBSCRIPTIONS_L6 AS (
  SELECT DISTINCT
    CUS_CUST_ID_BUY
  FROM `meli-bi-data.WHOWNER.BT_MP_PAY_SUBSCRIPTION`
  WHERE SUB_STATUS IN ('active','ready')
    AND CUS_CUST_ID_SEL IN (797214326, 797215821, 797215856, 797215866, 797215778)
),
SUMMARY_MELIMAS AS (
  SELECT
    v.MONTH_ID,
    v.SIT_SITE_ID,
    v.PLATFORM_ACTUAL,
    COUNT(DISTINCT v.CUS_CUST_ID) AS TOTAL_VIEWERS,
    COUNT(DISTINCT s.CUS_CUST_ID_BUY) AS TOTAL_SUSCRIPTORES
  FROM VIEWERS_PLATFORM_LABELLED v
  LEFT JOIN SUBSCRIPTIONS_L6 s
    ON v.CUS_CUST_ID = s.CUS_CUST_ID_BUY
  GROUP BY 1, 2, 3
)
SELECT *
FROM SUMMARY_MELIMAS
ORDER BY MONTH_ID, SIT_SITE_ID, PLATFORM_ACTUAL;