DECLARE date_from DATE;
DECLARE date_to DATE;
SET date_from = '2025-04-01';
SET date_to = CURRENT_DATE - 1;

WITH FIRST_TV_PLAY_HISTORY AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    MIN(DS) AS FIRST_TV_PLAY_DS,
    MIN(START_PLAY_TIMESTAMP) AS FIRST_TV_PLAY_TIMESTAMP
  FROM meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS
  WHERE
    UPPER(DEVICE_PLATFORM) LIKE '%TV%'
    AND PLAYBACK_TIME_MILLISECONDS/1000 >= 20
    AND LOGGED_USER IS TRUE
  GROUP BY ALL
),
FIRST_TV_PLAY_DAY_OF_ANALYSIS AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    FIRST_TV_PLAY_DS AS DS,
    DATE_TRUNC(FIRST_TV_PLAY_DS, MONTH) AS MONTH_ID,
    FIRST_TV_PLAY_TIMESTAMP
  FROM FIRST_TV_PLAY_HISTORY
  WHERE
    FIRST_TV_PLAY_DS >= date_from
    AND FIRST_TV_PLAY_DS <= date_to
),
USERS_MOBILE_BEFORE_FIRST_PLAY AS (
  SELECT DISTINCT
    F.SIT_SITE_ID,
    F.USER_ID,
    F.DS,
    F.MONTH_ID
  FROM FIRST_TV_PLAY_DAY_OF_ANALYSIS AS F
  INNER JOIN meli-bi-data.WHOWNER.BT_MKT_MPLAY_SESSION AS S_MOBILE
    ON F.USER_ID = S_MOBILE.USER_ID
    AND F.SIT_SITE_ID = S_MOBILE.SIT_SITE_ID
    AND F.DS = S_MOBILE.DS
  WHERE
    UPPER(S_MOBILE.DEVICE_PLATFORM) LIKE '%MOBILE%'
    AND S_MOBILE.LOGGED_USER IS TRUE
    AND S_MOBILE.END_TIME_USERTIMESTAMP < F.FIRST_TV_PLAY_TIMESTAMP
),
INFLUENCED_USERS_MONTH_SITE AS (
  SELECT
    SIT_SITE_ID,
    MONTH_ID,
    COUNT(DISTINCT USER_ID) AS INFLUENCED_FIRST_TV_VIEWERS
  FROM USERS_MOBILE_BEFORE_FIRST_PLAY
  GROUP BY ALL
),
TOTAL_FIRST_TV_VIEWERS_MONTH_SITE AS (
  SELECT
    SIT_SITE_ID,
    MONTH_ID,
    COUNT(DISTINCT USER_ID) AS TOTAL_FIRST_TV_VIEWERS
  FROM FIRST_TV_PLAY_DAY_OF_ANALYSIS
  GROUP BY ALL
)
SELECT
  INF.MONTH_ID,
  SUM(INF.INFLUENCED_FIRST_TV_VIEWERS) AS USERS_MOBILE_BEFORE_FIRST_TV_PLAY,
  SUM(TD.TOTAL_FIRST_TV_VIEWERS) AS GRAND_TOTAL_FIRST_TV_VIEWERS,
  ROUND(SAFE_DIVIDE(SUM(INF.INFLUENCED_FIRST_TV_VIEWERS), SUM(TD.TOTAL_FIRST_TV_VIEWERS)), 3) AS MOBILE_TO_FIRST_TV_VIEWER_SHARE
FROM INFLUENCED_USERS_MONTH_SITE AS INF
INNER JOIN TOTAL_FIRST_TV_VIEWERS_MONTH_SITE AS TD
  ON INF.SIT_SITE_ID = TD.SIT_SITE_ID
  AND INF.MONTH_ID = TD.MONTH_ID
GROUP BY 1
ORDER BY 1;