DECLARE mes_inicial DATE DEFAULT DATE '2025-07-01';
DECLARE meses_hacia_atras INT64 DEFAULT 5;

WITH MESES_ANALISIS AS (
  SELECT month_id
  FROM UNNEST(
    GENERATE_DATE_ARRAY(
      DATE_SUB(mes_inicial, INTERVAL meses_hacia_atras - 1 MONTH),
      mes_inicial,
      INTERVAL 1 MONTH
    )
  ) AS month_id
),

FIRST_SMART_VIEW AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    MIN_BY(
      STRUCT(
        START_PLAY_TIMESTAMP AS FIRST_SMART_TIMESTAMP,
        DATE_TRUNC(DS, MONTH) AS FIRST_SMART_MONTH
      ),
      START_PLAY_TIMESTAMP
    ) AS FIRST_SMART_STRUCT
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND UPPER(DEVICE_PLATFORM) LIKE '%TV%'
    AND DS <= CURRENT_DATE() - 1
  GROUP BY SIT_SITE_ID, USER_ID
),

FILTERED_FIRST_SMART AS (
  SELECT
    SIT_SITE_ID,
    USER_ID,
    FIRST_SMART_STRUCT.FIRST_SMART_TIMESTAMP,
    FIRST_SMART_STRUCT.FIRST_SMART_MONTH
  FROM FIRST_SMART_VIEW
  JOIN MESES_ANALISIS M ON FIRST_SMART_STRUCT.FIRST_SMART_MONTH = M.month_id
),

LAST_VIEW_BEFORE_SMART AS (
  SELECT
    F.SIT_SITE_ID,
    F.USER_ID,
    F.FIRST_SMART_MONTH,
    MAX_BY(
      STRUCT(
        START_PLAY_TIMESTAMP AS LAST_TIMESTAMP,
        UPPER(DEVICE_PLATFORM) AS LAST_PLATFORM
      ),
      START_PLAY_TIMESTAMP
    ) AS LAST_BEFORE_STRUCT
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS` P
  JOIN FILTERED_FIRST_SMART F
    ON P.USER_ID = F.USER_ID AND P.SIT_SITE_ID = F.SIT_SITE_ID
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND START_PLAY_TIMESTAMP < F.FIRST_SMART_TIMESTAMP
    AND DS <= CURRENT_DATE() - 1
  GROUP BY F.SIT_SITE_ID, F.USER_ID, F.FIRST_SMART_MONTH
),

SUMMARY AS (
  SELECT
    FIRST_SMART_MONTH AS MONTH_ID,
    CASE
      WHEN LAST_BEFORE_STRUCT.LAST_PLATFORM LIKE '%TV%' THEN 'SMART'
      WHEN LAST_BEFORE_STRUCT.LAST_PLATFORM LIKE '%MOBILE%' THEN 'MOBILE'
      WHEN LAST_BEFORE_STRUCT.LAST_PLATFORM LIKE '%DESKTOP%' THEN 'DESKTOP'
      WHEN LAST_BEFORE_STRUCT.LAST_PLATFORM LIKE '%CAST%' THEN 'CAST'
      ELSE 'UNKNOWN'
    END AS PLATFORM_PREV,
    COUNT(DISTINCT USER_ID) AS TOTAL_USERS
  FROM LAST_VIEW_BEFORE_SMART
  GROUP BY 1, 2
)

SELECT * FROM SUMMARY
ORDER BY MONTH_ID, TOTAL_USERS DESC;
