WITH BUYERS_MARKETPLACE AS (
  SELECT DISTINCT 
    DATE_TRUNC(bd.ord_created_dt, MONTH) AS MONTH_ID,
    bd.sit_site_id AS SIT_SITE_ID,
    CAST(bd.ord_buyer.id AS STRING) AS USER_ID
  FROM `meli-bi-data.WHOWNER.BT_ORD_ORDERS` AS bd
  WHERE bd.ord_tgmv_flg = TRUE
    AND COALESCE(bd.ord_auto_offer_flg, FALSE) = FALSE
    AND bd.sit_site_id IN ('MLA','MLM','MLC','MCO','MLU','MPE','MLB', 'MEC')
    AND bd.ord_closed_dt IS NOT NULL
    AND bd.ord_category.marketplace_id = 'TM'
    AND ord_order_mshops_flg = FALSE
    AND ord_order_proximity_flg = FALSE
    AND bd.ord_created_dt >= '2023-01-01'
),

VIEWERS_PLATFORM AS (
  SELECT
    DATE_TRUNC(DS, MONTH) AS MONTH_ID,
    SIT_SITE_ID,
    CAST(USER_ID AS STRING) AS USER_ID,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%TV%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_TV,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%MOBILE%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_MOBILE,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%DESK%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_DESKTOP,
    SUM(CASE WHEN UPPER(DEVICE_PLATFORM) LIKE '%CAST%' THEN PLAYBACK_TIME_MILLISECONDS / 60000 ELSE 0 END) AS TOTAL_CAST
  FROM `meli-bi-data.WHOWNER.BT_MKT_MPLAY_PLAYS`
  WHERE PLAYBACK_TIME_MILLISECONDS / 1000 >= 20
    AND DS <= CURRENT_DATE() - 1
  GROUP BY 1, 2, 3
),

VIEWERS_PLATFORM_LABELLED AS (
  SELECT
    MONTH_ID,
    SIT_SITE_ID,
    USER_ID,
    CONCAT(
      CASE WHEN TOTAL_TV > 0 THEN 'SMART' ELSE '' END,
      CASE WHEN TOTAL_MOBILE > 0 THEN 'MOBILE' ELSE '' END,
      CASE WHEN TOTAL_DESKTOP > 0 THEN 'DESKTOP' ELSE '' END,
      CASE WHEN TOTAL_CAST > 0 THEN 'CAST' ELSE '' END
    ) AS PLATFORM_ACTUAL
  FROM VIEWERS_PLATFORM
),

SUMMARY AS (
  SELECT
    v.MONTH_ID,
    v.SIT_SITE_ID,
    v.PLATFORM_ACTUAL,
      CASE WHEN SAFE_CAST(USER_ID AS INT64) IS NULL THEN 'NOT_LOG'
       ELSE 'LOG' 
       END AS FLAG_LOG,
    COUNT(DISTINCT v.USER_ID) AS TOTAL_VIEWERS,
    COUNT(DISTINCT b.USER_ID) AS TOTAL_BUYERS
  FROM VIEWERS_PLATFORM_LABELLED v
  LEFT JOIN BUYERS_MARKETPLACE b
    ON v.USER_ID = b.USER_ID
    AND v.MONTH_ID = b.MONTH_ID
    AND v.SIT_SITE_ID = b.SIT_SITE_ID
  GROUP BY 1, 2, 3, 4
)

SELECT *
FROM SUMMARY
ORDER BY MONTH_ID, SIT_SITE_ID, PLATFORM_ACTUAL;